// LISTA OFICIAL DE CÓDIGOS DE TRIBUTAÇÃO NACIONAL (cTribNac) — DADO, não regra. Gerado, não escrito.
//
// ⚠ ARQUIVO GERADO. Não editar à mão.
//   node apps/api/scripts/gerar-lista-servico-nacional.mjs
//
// FONTE: https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica/documentacao-atual/anexo_b-nbs2-lista_servico_nacional-snnfse.xlsx
//        (página: https://www.gov.br/nfse/pt-br/mei-e-demais-empresas/codigos-de-tributacao-nacional-nbs)
// ARQUIVO: docs/lista-servico-nacional/anexo_b-nbs2-lista_servico_nacional-snnfse.xlsx
//          SHA-256 a588fea05010a037826d826dd74520e32651bee926f2faa1ffd2794fba55d424
// ABA: LISTA.SERV.NAC.
// EXTRAÍDO EM: 2026-08-16
// REGISTROS: 335 códigos selecionáveis + 242 linhas de agrupamento
//            (577 linhas de dados na planilha).
//
// ⚠ O cTribNac NÃO É O ITEM DA LC 116. Ele é `item(2) + subitem(2) + desdobro nacional(2)` = 6
// dígitos. O item LC 116 `31.01` é "serviços técnicos em … telecomunicações e congêneres"; o
// código nacional `310104` é o desdobramento "Serviços técnicos em telecomunicações" — e é esse
// que aparece no DANFSe. Carregar só o anexo da LC 116 daria a granularidade ERRADA, e o erro
// sairia como nota emitida com o serviço errado.
//
// ⚠ A ARMADILHA DA PLANILHA, MEDIDA: a coluna do código é NUMÉRICA, e `010101` sai do arquivo
// como o número `10101` — o zero à esquerda some. Os códigos abaixo estão com padding para 6, e
// o gerador PROVA o padding conferindo cada um contra as colunas ITEM/SUBITEM/DESDOBRO da própria
// planilha (335/335 conferem; qualquer divergência aborta a geração).
//
// ⚠ LINHAS SEM CÓDIGO NA PLANILHA SÃO AGRUPAMENTO, não serviço. Elas dão o nome do ITEM e do
// SUBITEM, e é por isso que estão aqui em `GRUPOS_SERVICO_NACIONAL` em vez de descartadas: é o
// texto do grupo que faz alguém achar o código certo. Elas NÃO são selecionáveis.
//
// ⚠ ESTA LISTA VAI ENVELHECER (a Receita publica novas versões do Anexo B). PARA ATUALIZAR:
//   1. baixe o XLSX da URL acima para `docs/lista-servico-nacional/`;
//   2. atualize o hash e a data em `docs/lista-servico-nacional/README.md`;
//   3. ajuste `EXTRAIDO_EM` no gerador e rode-o;
//   4. rode `npm test -w @contabilidade/web` — há teste travando contagem, padding e o primeiro
//      código da lista (`010101`, nunca `10101`).
//
// Formato: `[código (6 dígitos), descrição]`. Tupla em vez de objeto porque são 335 linhas;
// o arquivo é carregado por import() dinâmico e não entra no bundle inicial.

export const SERVICOS_NACIONAIS = [
  ["010101","Análise e desenvolvimento de sistemas."],
  ["010201","Programação."],
  ["010301","Processamento de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres."],
  ["010302","Armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres."],
  ["010401","Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets, smartphones e congêneres."],
  ["010501","Licenciamento ou cessão de direito de uso de programas de computação."],
  ["010601","Assessoria e consultoria em informática."],
  ["010701","Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados."],
  ["010801","Planejamento, confecção, manutenção e atualização de páginas eletrônicas."],
  ["010901","Disponibilização, sem cessão definitiva, de conteúdos de áudio por meio da internet (exceto a distribuição de conteúdos pelas prestadoras de Serviço de Acesso Condicionado, de que trata a Lei nº 12.485, de 12 de setembro de 2011, sujeita ao ICMS)."],
  ["010902","Disponibilização, sem cessão definitiva, de conteúdos de vídeo, imagem e texto por meio da internet, respeitada a imunidade de livros, jornais e periódicos (exceto a distribuição de conteúdos pelas prestadoras de Serviço de Acesso Condicionado, de que trata a Lei nº 12.485, de 12 de setembro de 2011, sujeita ao ICMS)."],
  ["020101","Serviços de pesquisas e desenvolvimento de qualquer natureza."],
  ["030201","Cessão de direito de uso de marcas e de sinais de propaganda."],
  ["030301","Exploração de salões de festas, centro de convenções, stands e congêneres, para realização de eventos ou negócios de qualquer natureza."],
  ["030302","Exploração de escritórios virtuais e congêneres, para realização de eventos ou negócios de qualquer natureza."],
  ["030303","Exploração de quadras esportivas, estádios, ginásios, canchas e congêneres, para realização de eventos ou negócios de qualquer natureza."],
  ["030304","Exploração de auditórios, casas de espetáculos e congêneres, para realização de eventos ou negócios de qualquer natureza."],
  ["030305","Exploração de parques de diversões e congêneres, para realização de eventos ou negócios de qualquer natureza."],
  ["030401","Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia."],
  ["030402","Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de rodovia."],
  ["030403","Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de postes, cabos, dutos e condutos de qualquer natureza."],
  ["030501","Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário."],
  ["040101","Medicina."],
  ["040102","Biomedicina."],
  ["040201","Análises clínicas e congêneres."],
  ["040202","Patologia e congêneres."],
  ["040203","Eletricidade médica (eletroestimulação de nervos e musculos, cardioversão, etc) e congêneres."],
  ["040204","Radioterapia, quimioterapia e congêneres."],
  ["040205","Ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres."],
  ["040301","Hospitais e congêneres."],
  ["040302","Laboratórios e congêneres."],
  ["040303","Clínicas, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres."],
  ["040401","Instrumentação cirúrgica."],
  ["040501","Acupuntura."],
  ["040601","Enfermagem, inclusive serviços auxiliares."],
  ["040701","Serviços farmacêuticos."],
  ["040801","Terapia ocupacional."],
  ["040802","Fisioterapia."],
  ["040803","Fonoaudiologia."],
  ["040901","Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental."],
  ["041001","Nutrição."],
  ["041101","Obstetrícia."],
  ["041201","Odontologia."],
  ["041301","Ortóptica."],
  ["041401","Próteses sob encomenda."],
  ["041501","Psicanálise."],
  ["041601","Psicologia."],
  ["041701","Casas de repouso e congêneres."],
  ["041702","Casas de recuperação e congêneres."],
  ["041703","Creches e congêneres."],
  ["041704","Asilos e congêneres."],
  ["041801","Inseminação artificial, fertilização in vitro e congêneres."],
  ["041901","Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres."],
  ["042001","Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."],
  ["042101","Unidade de atendimento, assistência ou tratamento móvel e congêneres."],
  ["042201","Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres."],
  ["042301","Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário."],
  ["050101","Medicina veterinária"],
  ["050102","Zootecnia."],
  ["050201","Hospitais e congêneres, na área veterinária."],
  ["050202","Clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária."],
  ["050301","Laboratórios de análise na área veterinária."],
  ["050401","Inseminação artificial, fertilização in vitro e congêneres."],
  ["050501","Bancos de sangue e de órgãos e congêneres."],
  ["050601","Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."],
  ["050701","Unidade de atendimento, assistência ou tratamento móvel e congêneres."],
  ["050801","Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres."],
  ["050901","Planos de atendimento e assistência médico-veterinária."],
  ["060101","Barbearia, cabeleireiros, manicuros, pedicuros e congêneres."],
  ["060201","Esteticistas, tratamento de pele, depilação e congêneres."],
  ["060301","Banhos, duchas, sauna, massagens e congêneres."],
  ["060401","Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas."],
  ["060501","Centros de emagrecimento, spa e congêneres."],
  ["060601","Aplicação de tatuagens, piercings e congêneres."],
  ["070101","Engenharia e congêneres."],
  ["070102","Agronomia e congêneres."],
  ["070103","Agrimensura e congêneres."],
  ["070104","Arquitetura, urbanismo e congêneres."],
  ["070105","Geologia e congêneres."],
  ["070106","Paisagismo e congêneres."],
  ["070201","Execução, por administração, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação, concretagem e a instalação e montagem de produtos, peças e equipamentos (exceto o fornecimento de mercadorias produzidas pelo prestador de serviços fora do local da prestação dos serviços, que fica sujeito ao ICMS)."],
  ["070202","Execução, por empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação, concretagem e a instalação e montagem de produtos, peças e equipamentos (exceto o fornecimento de mercadorias produzidas pelo prestador de serviços fora do local da prestação dos serviços, que fica sujeito ao ICMS)."],
  ["070301","Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com obras e serviços de engenharia."],
  ["070302","Elaboração de anteprojetos, projetos básicos e projetos executivos para trabalhos de engenharia."],
  ["070401","Demolição."],
  ["070501","Reparação, conservação e reforma de edifícios e congêneres (exceto o fornecimento de mercadorias produzidas pelo prestador dos serviços, fora do local da prestação dos serviços, que fica sujeito ao ICMS)."],
  ["070502","Reparação, conservação e reforma de estradas, pontes, portos e congêneres (exceto o fornecimento de mercadorias produzidas pelo prestador dos serviços, fora do local da prestação dos serviços, que fica sujeito ao ICMS)."],
  ["070601","Colocação e instalação de tapetes, carpetes, cortinas e congêneres, com material fornecido pelo tomador do serviço."],
  ["070602","Colocação e instalação de assoalhos, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres, com material fornecido pelo tomador do serviço."],
  ["070701","Recuperação, raspagem, polimento e lustração de pisos e congêneres."],
  ["070801","Calafetação."],
  ["070901","Varrição, coleta e remoção de lixo, rejeitos e outros resíduos quaisquer."],
  ["070902","Incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer."],
  ["071001","Limpeza, manutenção e conservação de vias e logradouros públicos, parques, jardins e congêneres."],
  ["071002","Limpeza, manutenção e conservação de imóveis, chaminés, piscinas e congêneres."],
  ["071101","Decoração."],
  ["071102","Jardinagem, inclusive corte e poda de árvores."],
  ["071201","Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos."],
  ["071301","Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres."],
  ["071601","Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal e dos serviços congêneres indissociáveis da formação, manutenção e colheita de florestas, para quaisquer fins e por quaisquer meios."],
  ["071701","Escoramento, contenção de encostas e serviços congêneres."],
  ["071801","Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres."],
  ["071901","Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo."],
  ["072001","Aerofotogrametria (inclusive interpretação), cartografia, mapeamento e congêneres."],
  ["072002","Levantamentos batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres."],
  ["072003","Levantamentos topográficos e congêneres."],
  ["072101","Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, estimulação e outros serviços relacionados com a exploração e explotação de petróleo, gás natural e de outros recursos minerais."],
  ["072201","Nucleação e bombardeamento de nuvens e congêneres."],
  ["080101","Ensino regular pré-escolar, fundamental e médio."],
  ["080102","Ensino regular superior."],
  ["080201","Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza."],
  ["090101","Hospedagem em hotéis, hotelaria marítima e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."],
  ["090102","Hospedagem em pensões, albergues, pousadas, hospedarias, ocupação por temporada com fornecimento de serviços e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."],
  ["090103","Hospedagem em motéis e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."],
  ["090104","Hospedagem em apart-service condominiais, flat, apart-hotéis, hotéis residência, residence-service, suite service e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."],
  ["090201","Agenciamento e intermediação de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres."],
  ["090202","Organização, promoção e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres."],
  ["090301","Guias de turismo."],
  ["100101","Agenciamento, corretagem ou intermediação de câmbio."],
  ["100102","Agenciamento, corretagem ou intermediação de seguros."],
  ["100103","Agenciamento, corretagem ou intermediação de cartões de crédito."],
  ["100104","Agenciamento, corretagem ou intermediação de planos de saúde."],
  ["100105","Agenciamento, corretagem ou intermediação de planos de previdência privada."],
  ["100201","Agenciamento, corretagem ou intermediação de títulos em geral e valores mobiliários."],
  ["100202","Agenciamento, corretagem ou intermediação de contratos quaisquer."],
  ["100301","Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária."],
  ["100401","Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing)."],
  ["100402","Agenciamento, corretagem ou intermediação de contratos de franquia (franchising)."],
  ["100403","Agenciamento, corretagem ou intermediação de faturização (factoring)."],
  ["100501","Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens ou subitens, por quaisquer meios."],
  ["100502","Agenciamento, corretagem ou intermediação de bens móveis ou imóveis realizados no âmbito de Bolsas de Mercadorias e Futuros, por quaisquer meios."],
  ["100601","Agenciamento marítimo."],
  ["100701","Agenciamento de notícias."],
  ["100801","Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios."],
  ["100901","Representação de qualquer natureza, inclusive comercial."],
  ["101001","Distribuição de bens de terceiros."],
  ["110101","Guarda e estacionamento de veículos terrestres automotores."],
  ["110102","Guarda e estacionamento de aeronaves e de embarcações."],
  ["110201","Vigilância, segurança ou monitoramento de bens, pessoas e semoventes."],
  ["110301","Escolta, inclusive de veículos e cargas."],
  ["110401","Armazenamento, depósito, guarda de bens de qualquer espécie."],
  ["110402","Carga, descarga, arrumação de bens de qualquer espécie."],
  ["110501","Serviços relacionados ao monitoramento e rastreamento a distância, em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação ou movimento, realizados por meio de telefonia móvel, transmissão de satélites, rádio ou qualquer outro meio, inclusive pelas empresas de Tecnologia da Informação Veicular, independentemente de o prestador de serviços ser proprietário ou não da infraestrutura de telecomunicações que utiliza."],
  ["120101","Espetáculos teatrais."],
  ["120201","Exibições cinematográficas."],
  ["120301","Espetáculos circenses."],
  ["120401","Programas de auditório."],
  ["120501","Parques de diversões, centros de lazer e congêneres."],
  ["120601","Boates, taxi-dancing e congêneres."],
  ["120701","Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres."],
  ["120801","Feiras, exposições, congressos e congêneres."],
  ["120901","Bilhares."],
  ["120902","Boliches."],
  ["120903","Diversões eletrônicas ou não."],
  ["121001","Corridas e competições de animais."],
  ["121101","Competições esportivas ou de destreza física ou intelectual, com ou sem a participação do espectador."],
  ["121201","Execução de música."],
  ["121301","Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres."],
  ["121401","Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo."],
  ["121501","Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres."],
  ["121601","Exibição de filmes, entrevistas, musicais, espetáculos, shows, concertos, desfiles, óperas, competições esportivas, de destreza intelectual ou congêneres."],
  ["121701","Recreação e animação, inclusive em festas e eventos de qualquer natureza."],
  ["130201","Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres."],
  ["130301","Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres."],
  ["130401","Reprografia, microfilmagem e digitalização."],
  ["130501","Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia, exceto se destinados a posterior operação de comercialização ou industrialização, ainda que incorporados, de qualquer forma, a outra mercadoria que deva ser objeto de posterior circulação, tais como bulas, rótulos, etiquetas, caixas, cartuchos, embalagens e manuais técnicos e de instrução, quando ficarão sujeitos ao ICMS."],
  ["140101","Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."],
  ["140201","Assistência técnica."],
  ["140301","Recondicionamento de motores (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."],
  ["140401","Recauchutagem ou regeneração de pneus."],
  ["140501","Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer."],
  ["140601","Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido."],
  ["140701","Colocação de molduras e congêneres."],
  ["140801","Encadernação, gravação e douração de livros, revistas e congêneres."],
  ["140901","Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento."],
  ["141001","Tinturaria e lavanderia."],
  ["141101","Tapeçaria e reforma de estofamentos em geral."],
  ["141201","Funilaria e lanternagem."],
  ["141301","Carpintaria."],
  ["141302","Serralheria."],
  ["141401","Guincho intramunicipal."],
  ["141402","Guindaste e içamento."],
  ["150101","Administração de fundos quaisquer e congêneres."],
  ["150102","Administração de consórcio e congêneres."],
  ["150103","Administração de cartão de crédito ou débito e congêneres."],
  ["150104","Administração de carteira de clientes e congêneres."],
  ["150105","Administração de cheques pré-datados e congêneres."],
  ["150201","Abertura de conta-corrente no País, bem como a manutenção da referida conta ativa e inativa."],
  ["150202","Abertura de conta-corrente no exterior, bem como a manutenção da referida conta ativa e inativa."],
  ["150203","Abertura de conta de investimentos e aplicação no País, bem como a manutenção da referida conta ativa e inativa."],
  ["150204","Abertura de conta de investimentos e aplicação no exterior, bem como a manutenção da referida conta ativa e inativa."],
  ["150205","Abertura de caderneta de poupança no País, bem como a manutenção da referida conta ativa e inativa."],
  ["150206","Abertura de caderneta de poupança no exterior, bem como a manutenção da referida conta ativa e inativa."],
  ["150207","Abertura de contas em geral no País, não abrangida em outro subitem, bem como a manutenção das referidas contas ativas e inativas."],
  ["150208","Abertura de contas em geral no exterior, não abrangida em outro subitem, bem como a manutenção das referidas contas ativas e inativas."],
  ["150301","Locação de cofres particulares."],
  ["150302","Manutenção de cofres particulares."],
  ["150303","Locação de terminais eletrônicos."],
  ["150304","Manutenção de terminais eletrônicos."],
  ["150305","Locação de terminais de atendimento."],
  ["150306","Manutenção de terminais de atendimento."],
  ["150307","Locação de bens e equipamentos em geral."],
  ["150308","Manutenção de bens e equipamentos em geral."],
  ["150401","Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade, atestado de capacidade financeira e congêneres."],
  ["150501","Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres."],
  ["150502","Inclusão no Cadastro de Emitentes de Cheques sem Fundos - CCF."],
  ["150503","Exclusão no Cadastro de Emitentes de Cheques sem Fundos - CCF."],
  ["150504","Inclusão em quaisquer outros bancos cadastrais."],
  ["150505","Exclusão em quaisquer outros bancos cadastrais."],
  ["150601","Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral"],
  ["150602","Abono de firmas."],
  ["150603","Coleta e entrega de documentos, bens e valores."],
  ["150604","Comunicação com outra agência ou com a administração central."],
  ["150605","Licenciamento eletrônico de veículos."],
  ["150606","Transferência de veículos."],
  ["150607","Agenciamento fiduciário ou depositário."],
  ["150608","Devolução de bens em custódia."],
  ["150701","Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo, inclusive por telefone, fac-símile, internet e telex."],
  ["150702","Acesso a terminais de atendimento, inclusive vinte e quatro horas."],
  ["150703","Acesso a outro banco e à rede compartilhada."],
  ["150704","Fornecimento de saldo, extrato e demais informações relativas a contas em geral, por qualquer meio ou processo."],
  ["150801","Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito."],
  ["150802","Estudo, análise e avaliação de operações de crédito."],
  ["150803","Emissão, concessão, alteração ou contratação de aval, fiança, anuência e congêneres."],
  ["150804","Serviços relativos à abertura de crédito, para quaisquer fins."],
  ["150901","Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia, alteração, cancelamento e registro de contrato, e demais serviços relacionados ao arrendamento mercantil (leasing)."],
  ["151001","Serviços relacionados a cobranças em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento."],
  ["151002","Serviços relacionados a recebimentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento."],
  ["151003","Serviços relacionados a pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento."],
  ["151004","Serviços relacionados a fornecimento de posição de cobrança, recebimento ou pagamento."],
  ["151005","Serviços relacionados a emissão de carnês, fichas de compensação, impressos e documentos em geral."],
  ["151101","Devolução de títulos, protesto de títulos, sustação de protesto, manutenção de títulos, reapresentação de títulos, e demais serviços a eles relacionados."],
  ["151201","Custódia em geral, inclusive de títulos e valores mobiliários."],
  ["151301","Serviços relacionados a operações de câmbio em geral, edição, alteração, prorrogação, cancelamento e baixa de contrato de câmbio."],
  ["151302","Serviços relacionados a emissão de registro de exportação ou de crédito."],
  ["151303","Serviços relacionados a cobrança ou depósito no exterior."],
  ["151304","Serviços relacionados a emissão, fornecimento e cancelamento de cheques de viagem."],
  ["151305","Serviços relacionados a fornecimento, transferência, cancelamento e demais serviços relativos a carta de crédito de importação, exportação e garantias recebidas."],
  ["151306","Serviços relacionados a envio e recebimento de mensagens em geral relacionadas a operações de câmbio."],
  ["151401","Fornecimento, emissão, reemissão de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."],
  ["151402","Renovação de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."],
  ["151403","Manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."],
  ["151501","Compensação de cheques e títulos quaisquer."],
  ["151502","Serviços relacionados a depósito, inclusive depósito identificado, a saque de contas quaisquer, por qualquer meio ou processo, inclusive em terminais eletrônicos e de atendimento."],
  ["151601","Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo."],
  ["151602","Serviços relacionados à transferência de valores, dados, fundos, pagamentos e similares, inclusive entre contas em geral."],
  ["151701","Emissão e fornecimento de cheques quaisquer, avulso ou por talão."],
  ["151702","Devolução de cheques quaisquer, avulso ou por talão."],
  ["151703","Sustação, cancelamento e oposição de cheques quaisquer, avulso ou por talão."],
  ["151801","Serviços relacionados a crédito imobiliário, de avaliação e vistoria de imóvel ou obra."],
  ["151802","Serviços relacionados a crédito imobiliário, de análise técnica e jurídica."],
  ["151803","Serviços relacionados a crédito imobiliário, de emissão, reemissão, alteração, transferência e renegociação de contrato."],
  ["151804","Serviços relacionados a crédito imobiliário, de emissão e reemissão do termo de quitação."],
  ["151805","Demais serviços relacionados a crédito imobiliário."],
  ["160101","Serviços de transporte coletivo municipal rodoviário de passageiros."],
  ["160102","Serviços de transporte coletivo municipal metroviário de passageiros."],
  ["160103","Serviços de transporte coletivo municipal ferroviário de passageiros."],
  ["160104","Serviços de transporte coletivo municipal aquaviário de passageiros."],
  ["160201","Outros serviços de transporte de natureza municipal."],
  ["170101","Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista."],
  ["170102","Análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza, inclusive cadastro e similares."],
  ["170201","Datilografia, digitação, estenografia e congêneres."],
  ["170202","Expediente, secretaria em geral, apoio e infra-estrutura administrativa e congêneres."],
  ["170203","Resposta audível e congêneres."],
  ["170204","Redação, edição, revisão e congêneres."],
  ["170205","Interpretação, tradução e congêneres."],
  ["170301","Planejamento, coordenação, programação ou organização técnica."],
  ["170302","Planejamento, coordenação, programação ou organização financeira."],
  ["170303","Planejamento, coordenação, programação ou organização administrativa."],
  ["170401","Recrutamento, agenciamento, seleção e colocação de mão-de-obra."],
  ["170501","Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço."],
  ["170601","Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade, elaboração de desenhos, textos e demais materiais publicitários."],
  ["170801","Franquia (franchising)."],
  ["170901","Perícias, laudos, exames técnicos e análises técnicas."],
  ["171001","Planejamento, organização e administração de feiras, exposições, e congêneres."],
  ["171002","Planejamento, organização e administração de congressos e congêneres."],
  ["171101","Organização de festas e recepções."],
  ["171102","Bufê (exceto o fornecimento de alimentação e bebidas, que fica sujeito ao ICMS)."],
  ["171201","Administração em geral, inclusive de bens e negócios de terceiros."],
  ["171301","Leilão e congêneres."],
  ["171401","Advocacia"],
  ["171501","Arbitragem de qualquer espécie, inclusive jurídica."],
  ["171601","Auditoria."],
  ["171701","Análise de Organização e Métodos."],
  ["171801","Atuária e cálculos técnicos de qualquer natureza."],
  ["171901","Contabilidade, inclusive serviços técnicos e auxiliares."],
  ["172001","Consultoria e assessoria econômica ou financeira."],
  ["172101","Estatística."],
  ["172201","Cobrança em geral."],
  ["172301","Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar e em geral, relacionados a operações de faturização (factoring)."],
  ["172401","Apresentação de palestras, conferências, seminários e congêneres."],
  ["172501","Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio (exceto em livros, jornais, periódicos e nas modalidades de serviços de radiodifusão sonora e de sons e imagens de recepção livre e gratuita)."],
  ["180101","Serviços de regulação de sinistros vinculados a contratos de seguros e congêneres."],
  ["180102","Serviços de inspeção e avaliação de riscos para cobertura de contratos de seguros e congêneres."],
  ["180103","Serviços de prevenção e gerência de riscos seguráveis e congêneres."],
  ["190101","Serviços de distribuição e venda de bilhetes e demais produtos de loteria, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres."],
  ["190102","Serviços de distribuição e venda de bingos e congêneres."],
  ["200101","Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, rebocador escoteiro, atracação, desatracação, serviços de praticagem, capatazia, armazenagem de qualquer natureza, serviços acessórios, movimentação de mercadorias, serviços de apoio marítimo, de movimentação ao largo, serviços de armadores, estiva, conferência, logística e congêneres."],
  ["200201","Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem de qualquer natureza, capatazia, movimentação de aeronaves, serviços de apoio aeroportuários, serviços acessórios, movimentação de mercadorias, logística e congêneres."],
  ["200301","Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros, mercadorias, inclusive suas operações, logística e congêneres."],
  ["210101","Serviços de registros públicos, cartorários e notariais."],
  ["220101","Serviços de exploração de rodovia mediante cobrança de preço ou pedágio dos usuários, envolvendo execução de serviços de conservação, manutenção, melhoramentos para adequação de capacidade e segurança de trânsito, operação, monitoração, assistência aos usuários e outros serviços definidos em contratos, atos de concessão ou de permissão ou em normas oficiais."],
  ["230101","Serviços de programação e comunicação visual e congêneres."],
  ["230102","Serviços de desenho industrial e congêneres."],
  ["240101","Serviços de chaveiros, confecção de carimbos e congêneres."],
  ["240102","Serviços de placas, sinalização visual, banners, adesivos e congêneres."],
  ["250101","Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico; fornecimento de flores, coroas e outros paramentos; desembaraço de certidão de óbito; fornecimento de véu, essa e outros adornos; embalsamento, embelezamento, conservação ou restauração de cadáveres."],
  ["250201","Translado intramunicipal de corpos e partes de corpos cadavéricos."],
  ["250202","Cremação de corpos e partes de corpos cadavéricos."],
  ["250301","Planos ou convênio funerários."],
  ["250401","Manutenção e conservação de jazigos e cemitérios."],
  ["250501","Cessão de uso de espaços em cemitérios para sepultamento."],
  ["260101","Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas."],
  ["260102","Serviços de courrier e congêneres."],
  ["270101","Serviços de assistência social."],
  ["280101","Serviços de avaliação de bens e serviços de qualquer natureza."],
  ["290101","Serviços de biblioteconomia."],
  ["300101","Serviços de biologia e biotecnologia."],
  ["300102","Serviços de química."],
  ["310101","Serviços técnicos em edificações e congêneres."],
  ["310102","Serviços técnicos em eletrônica, eletrotécnica e congêneres."],
  ["310103","Serviços técnicos em mecânica e congêneres."],
  ["310104","Serviços técnicos em telecomunicações e congêneres."],
  ["320101","Serviços de desenhos técnicos."],
  ["330101","Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres."],
  ["340101","Serviços de investigações particulares, detetives e congêneres."],
  ["350101","Serviços de reportagem e jornalismo."],
  ["350102","Serviços de assessoria de imprensa."],
  ["350103","Serviços de relações públicas."],
  ["360101","Serviços de meteorologia."],
  ["370101","Serviços de artistas, atletas, modelos e manequins."],
  ["380101","Serviços de museologia."],
  ["390101","Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço)."],
  ["400101","Obras de arte sob encomenda."],
  ["990101","Serviços sem a incidência de ISSQN e ICMS"],
];

// Agrupamento: `[chave, descrição]`. Chave de 2 dígitos = ITEM (ex.: "01"); de 4 = SUBITEM
// (ex.: "0101"). São os PREFIXOS do próprio código — nada aqui é derivado por semelhança de texto.
export const GRUPOS_SERVICO_NACIONAL = [
  ["01","Serviços de Informática e congêneres."],
  ["0101","Análise e desenvolvimento de sistemas."],
  ["0102","Programação."],
  ["0103","Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres."],
  ["0104","Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets, smartphones e congêneres."],
  ["0105","Licenciamento ou cessão de direito de uso de programas de computação."],
  ["0106","Assessoria e consultoria em informática."],
  ["0107","Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados."],
  ["0108","Planejamento, confecção, manutenção e atualização de páginas eletrônicas."],
  ["0109","Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet, respeitada a imunidade de livros, jornais e periódicos (exceto a distribuição de conteúdos pelas prestadoras de Serviço de Acesso Condicionado, de que trata a Lei nº 12.485, de 12 de setembro de 2011, sujeita ao ICMS)."],
  ["02","Serviços de pesquisas e desenvolvimento de qualquer natureza."],
  ["0201","Serviços de pesquisas e desenvolvimento de qualquer natureza."],
  ["03","Serviços prestados mediante locação, cessão de direito de uso e congêneres."],
  ["0302","Cessão de direito de uso de marcas e de sinais de propaganda."],
  ["0303","Exploração de salões de festas, centro de convenções, escritórios virtuais, stands, quadras esportivas, estádios, ginásios, auditórios, casas de espetáculos, parques de diversões, canchas e congêneres, para realização de eventos ou negócios de qualquer natureza."],
  ["0304","Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza."],
  ["0305","Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário."],
  ["04","Serviços de saúde, assistência médica e congêneres."],
  ["0401","Medicina e biomedicina."],
  ["0402","Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres."],
  ["0403","Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres."],
  ["0404","Instrumentação cirúrgica."],
  ["0405","Acupuntura."],
  ["0406","Enfermagem, inclusive serviços auxiliares."],
  ["0407","Serviços farmacêuticos."],
  ["0408","Terapia ocupacional, fisioterapia e fonoaudiologia."],
  ["0409","Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental."],
  ["0410","Nutrição."],
  ["0411","Obstetrícia."],
  ["0412","Odontologia."],
  ["0413","Ortóptica."],
  ["0414","Próteses sob encomenda."],
  ["0415","Psicanálise."],
  ["0416","Psicologia."],
  ["0417","Casas de repouso e de recuperação, creches, asilos e congêneres."],
  ["0418","Inseminação artificial, fertilização in vitro e congêneres."],
  ["0419","Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres."],
  ["0420","Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."],
  ["0421","Unidade de atendimento, assistência ou tratamento móvel e congêneres."],
  ["0422","Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres."],
  ["0423","Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário."],
  ["05","Serviços de medicina e assistência veterinária e congêneres."],
  ["0501","Medicina veterinária e zootecnia."],
  ["0502","Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária."],
  ["0503","Laboratórios de análise na área veterinária."],
  ["0504","Inseminação artificial, fertilização in vitro e congêneres."],
  ["0505","Bancos de sangue e de órgãos e congêneres."],
  ["0506","Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."],
  ["0507","Unidade de atendimento, assistência ou tratamento móvel e congêneres."],
  ["0508","Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres."],
  ["0509","Planos de atendimento e assistência médico-veterinária."],
  ["06","Serviços de cuidados pessoais, estética, atividades físicas e congêneres."],
  ["0601","Barbearia, cabeleireiros, manicuros, pedicuros e congêneres."],
  ["0602","Esteticistas, tratamento de pele, depilação e congêneres."],
  ["0603","Banhos, duchas, sauna, massagens e congêneres."],
  ["0604","Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas."],
  ["0605","Centros de emagrecimento, spa e congêneres."],
  ["0606","Aplicação de tatuagens, piercings e congêneres."],
  ["07","Serviços relativos a engenharia, arquitetura, geologia, urbanismo, construção civil, manutenção, limpeza, meio ambiente, saneamento e congêneres."],
  ["0701","Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres."],
  ["0702","Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação, concretagem e a instalação e montagem de produtos, peças e equipamentos (exceto o fornecimento de mercadorias produzidas pelo prestador de serviços fora do local da prestação dos serviços, que fica sujeito ao ICMS)."],
  ["0703","Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com obras e serviços de engenharia; elaboração de anteprojetos, projetos básicos e projetos executivos para trabalhos de engenharia."],
  ["0704","Demolição."],
  ["0705","Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres (exceto o fornecimento de mercadorias produzidas pelo prestador dos serviços, fora do local da prestação dos serviços, que fica sujeito ao ICMS)."],
  ["0706","Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres, com material fornecido pelo tomador do serviço."],
  ["0707","Recuperação, raspagem, polimento e lustração de pisos e congêneres."],
  ["0708","Calafetação."],
  ["0709","Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer."],
  ["0710","Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres."],
  ["0711","Decoração e jardinagem, inclusive corte e poda de árvores."],
  ["0712","Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos."],
  ["0713","Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres."],
  ["0716","Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal e dos serviços congêneres indissociáveis da formação, manutenção e colheita de florestas, para quaisquer fins e por quaisquer meios."],
  ["0717","Escoramento, contenção de encostas e serviços congêneres."],
  ["0718","Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres."],
  ["0719","Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo."],
  ["0720","Aerofotogrametria (inclusive interpretação), cartografia, mapeamento, levantamentos topográficos, batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres."],
  ["0721","Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, estimulação e outros serviços relacionados com a exploração e explotação de petróleo, gás natural e de outros recursos minerais."],
  ["0722","Nucleação e bombardeamento de nuvens e congêneres."],
  ["08","Serviços de educação, ensino, orientação pedagógica e educacional, instrução, treinamento e avaliação pessoal de qualquer grau ou natureza."],
  ["0801","Ensino regular pré-escolar, fundamental, médio e superior."],
  ["0802","Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza."],
  ["09","Serviços relativos a hospedagem, turismo, viagens e congêneres."],
  ["0901","Hospedagem de qualquer natureza em hotéis, apart-service condominiais, flat, apart-hotéis, hotéis residência, residence-service, suite service, hotelaria marítima, motéis, pensões e congêneres; ocupação por temporada com fornecimento de serviço (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."],
  ["0902","Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres."],
  ["0903","Guias de turismo."],
  ["10","Serviços de intermediação e congêneres."],
  ["1001","Agenciamento, corretagem ou intermediação de câmbio, de seguros, de cartões de crédito, de planos de saúde e de planos de previdência privada."],
  ["1002","Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer."],
  ["1003","Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária."],
  ["1004","Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing), de franquia (franchising) e de faturização (factoring)."],
  ["1005","Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens ou subitens, inclusive aqueles realizados no âmbito de Bolsas de Mercadorias e Futuros, por quaisquer meios."],
  ["1006","Agenciamento marítimo."],
  ["1007","Agenciamento de notícias."],
  ["1008","Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios."],
  ["1009","Representação de qualquer natureza, inclusive comercial."],
  ["1010","Distribuição de bens de terceiros."],
  ["11","Serviços de guarda, estacionamento, armazenamento, vigilância e congêneres."],
  ["1101","Guarda e estacionamento de veículos terrestres automotores, de aeronaves e de embarcações."],
  ["1102","Vigilância, segurança ou monitoramento de bens, pessoas e semoventes."],
  ["1103","Escolta, inclusive de veículos e cargas."],
  ["1104","Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie."],
  ["1105","Serviços relacionados ao monitoramento e rastreamento a distância, em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação ou movimento, realizados por meio de telefonia móvel, transmissão de satélites, rádio ou qualquer outro meio, inclusive pelas empresas de Tecnologia da Informação Veicular, independentemente de o prestador de serviços ser proprietário ou não da infraestrutura de telecomunicações que utiliza."],
  ["12","Serviços de diversões, lazer, entretenimento e congêneres."],
  ["1201","Espetáculos teatrais."],
  ["1202","Exibições cinematográficas."],
  ["1203","Espetáculos circenses."],
  ["1204","Programas de auditório."],
  ["1205","Parques de diversões, centros de lazer e congêneres."],
  ["1206","Boates, taxi-dancing e congêneres."],
  ["1207","Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres."],
  ["1208","Feiras, exposições, congressos e congêneres."],
  ["1209","Bilhares, boliches e diversões eletrônicas ou não."],
  ["1210","Corridas e competições de animais."],
  ["1211","Competições esportivas ou de destreza física ou intelectual, com ou sem a participação do espectador."],
  ["1212","Execução de música."],
  ["1213","Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres."],
  ["1214","Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo."],
  ["1215","Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres."],
  ["1216","Exibição de filmes, entrevistas, musicais, espetáculos, shows, concertos, desfiles, óperas, competições esportivas, de destreza intelectual ou congêneres."],
  ["1217","Recreação e animação, inclusive em festas e eventos de qualquer natureza."],
  ["13","Serviços relativos a fonografia, fotografia, cinematografia e reprografia."],
  ["1302","Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres."],
  ["1303","Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres."],
  ["1304","Reprografia, microfilmagem e digitalização."],
  ["1305","Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia, exceto se destinados a posterior operação de comercialização ou industrialização, ainda que incorporados, de qualquer forma, a outra mercadoria que deva ser objeto de posterior circulação, tais como bulas, rótulos, etiquetas, caixas, cartuchos, embalagens e manuais técnicos e de instrução, quando ficarão sujeitos ao ICMS."],
  ["14","Serviços relativos a bens de terceiros."],
  ["1401","Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."],
  ["1402","Assistência técnica."],
  ["1403","Recondicionamento de motores (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."],
  ["1404","Recauchutagem ou regeneração de pneus."],
  ["1405","Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer."],
  ["1406","Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido."],
  ["1407","Colocação de molduras e congêneres."],
  ["1408","Encadernação, gravação e douração de livros, revistas e congêneres."],
  ["1409","Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento."],
  ["1410","Tinturaria e lavanderia."],
  ["1411","Tapeçaria e reforma de estofamentos em geral."],
  ["1412","Funilaria e lanternagem."],
  ["1413","Carpintaria e serralheria."],
  ["1414","Guincho intramunicipal, guindaste e içamento."],
  ["15","Serviços relacionados ao setor bancário ou financeiro, inclusive aqueles prestados por instituições financeiras autorizadas a funcionar pela União ou por quem de direito."],
  ["1501","Administração de fundos quaisquer, de consórcio, de cartão de crédito ou débito e congêneres, de carteira de clientes, de cheques pré-datados e congêneres."],
  ["1502","Abertura de contas em geral, inclusive conta-corrente, conta de investimentos e aplicação e caderneta de poupança, no País e no exterior, bem como a manutenção das referidas contas ativas e inativas."],
  ["1503","Locação e manutenção de cofres particulares, de terminais eletrônicos, de terminais de atendimento e de bens e equipamentos em geral."],
  ["1504","Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade, atestado de capacidade financeira e congêneres."],
  ["1505","Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres, inclusão ou exclusão no Cadastro de Emitentes de Cheques sem Fundos - CCF ou em quaisquer outros bancos cadastrais."],
  ["1506","Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral; abono de firmas; coleta e entrega de documentos, bens e valores; comunicação com outra agência ou com a administração central; licenciamento eletrônico de veículos; transferência de veículos; agenciamento fiduciário ou depositário; devolução de bens em custódia."],
  ["1507","Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo, inclusive por telefone, fac-símile, internet e telex, acesso a terminais de atendimento, inclusive vinte e quatro horas; acesso a outro banco e à rede compartilhada; fornecimento de saldo, extrato e demais informações relativas a contas em geral, por qualquer meio ou processo."],
  ["1508","Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito; estudo, análise e avaliação de operações de crédito; emissão, concessão, alteração ou contratação de aval, fiança, anuência e congêneres; serviços relativos à abertura de crédito, para quaisquer fins."],
  ["1509","Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia, alteração, cancelamento e registro de contrato, e demais serviços relacionados ao arrendamento mercantil (leasing)."],
  ["1510","Serviços relacionados a cobranças, recebimentos ou pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento; fornecimento de posição de cobrança, recebimento ou pagamento; emissão de carnês, fichas de compensação, impressos e documentos em geral."],
  ["1511","Devolução de títulos, protesto de títulos, sustação de protesto, manutenção de títulos, reapresentação de títulos, e demais serviços a eles relacionados."],
  ["1512","Custódia em geral, inclusive de títulos e valores mobiliários."],
  ["1513","Serviços relacionados a operações de câmbio em geral, edição, alteração, prorrogação, cancelamento e baixa de contrato de câmbio; emissão de registro de exportação ou de crédito; cobrança ou depósito no exterior; emissão, fornecimento e cancelamento de cheques de viagem; fornecimento, transferência, cancelamento e demais serviços relativos a carta de crédito de importação, exportação e garantias recebidas; envio e recebimento de mensagens em geral relacionadas a operações de câmbio."],
  ["1514","Fornecimento, emissão, reemissão, renovação e manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."],
  ["1515","Compensação de cheques e títulos quaisquer; serviços relacionados a depósito, inclusive depósito identificado, a saque de contas quaisquer, por qualquer meio ou processo, inclusive em terminais eletrônicos e de atendimento."],
  ["1516","Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo; serviços relacionados à transferência de valores, dados, fundos, pagamentos e similares, inclusive entre contas em geral."],
  ["1517","Emissão, fornecimento, devolução, sustação, cancelamento e oposição de cheques quaisquer, avulso ou por talão."],
  ["1518","Serviços relacionados a crédito imobiliário, avaliação e vistoria de imóvel ou obra, análise técnica e jurídica, emissão, reemissão, alteração, transferência e renegociação de contrato, emissão e reemissão do termo de quitação e demais serviços relacionados a crédito imobiliário."],
  ["16","Serviços de transporte de natureza municipal."],
  ["1601","Serviços de transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros."],
  ["1602","Outros serviços de transporte de natureza municipal."],
  ["17","Serviços de apoio técnico, administrativo, jurídico, contábil, comercial e congêneres."],
  ["1701","Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista; análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza, inclusive cadastro e similares."],
  ["1702","Datilografia, digitação, estenografia, expediente, secretaria em geral, resposta audível, redação, edição, interpretação, revisão, tradução, apoio e infra-estrutura administrativa e congêneres."],
  ["1703","Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa."],
  ["1704","Recrutamento, agenciamento, seleção e colocação de mão-de-obra."],
  ["1705","Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço."],
  ["1706","Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade, elaboração de desenhos, textos e demais materiais publicitários."],
  ["1708","Franquia (franchising)."],
  ["1709","Perícias, laudos, exames técnicos e análises técnicas."],
  ["1710","Planejamento, organização e administração de feiras, exposições, congressos e congêneres."],
  ["1711","Organização de festas e recepções; bufê (exceto o fornecimento de alimentação e bebidas, que fica sujeito ao ICMS)."],
  ["1712","Administração em geral, inclusive de bens e negócios de terceiros."],
  ["1713","Leilão e congêneres."],
  ["1714","Advocacia"],
  ["1715","Arbitragem de qualquer espécie, inclusive jurídica."],
  ["1716","Auditoria."],
  ["1717","Análise de Organização e Métodos."],
  ["1718","Atuária e cálculos técnicos de qualquer natureza."],
  ["1719","Contabilidade, inclusive serviços técnicos e auxiliares."],
  ["1720","Consultoria e assessoria econômica ou financeira."],
  ["1721","Estatística."],
  ["1722","Cobrança em geral."],
  ["1723","Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar e em geral, relacionados a operações de faturização (factoring)."],
  ["1724","Apresentação de palestras, conferências, seminários e congêneres."],
  ["1725","Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio (exceto em livros, jornais, periódicos e nas modalidades de serviços de radiodifusão sonora e de sons e imagens de recepção livre e gratuita)."],
  ["18","Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros; prevenção e gerência de riscos seguráveis e congêneres."],
  ["1801","Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros; prevenção e gerência de riscos seguráveis e congêneres."],
  ["19","Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres."],
  ["1901","Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres."],
  ["20","Serviços portuários, aeroportuários, ferroportuários, de terminais rodoviários, ferroviários e metroviários."],
  ["2001","Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, rebocador escoteiro, atracação, desatracação, serviços de praticagem, capatazia, armazenagem de qualquer natureza, serviços acessórios, movimentação de mercadorias, serviços de apoio marítimo, de movimentação ao largo, serviços de armadores, estiva, conferência, logística e congêneres."],
  ["2002","Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem de qualquer natureza, capatazia, movimentação de aeronaves, serviços de apoio aeroportuários, serviços acessórios, movimentação de mercadorias, logística e congêneres."],
  ["2003","Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros, mercadorias, inclusive suas operações, logística e congêneres."],
  ["21","Serviços de registros públicos, cartorários e notariais."],
  ["2101","Serviços de registros públicos, cartorários e notariais."],
  ["22","Serviços de exploração de rodovia."],
  ["2201","Serviços de exploração de rodovia mediante cobrança de preço ou pedágio dos usuários, envolvendo execução de serviços de conservação, manutenção, melhoramentos para adequação de capacidade e segurança de trânsito, operação, monitoração, assistência aos usuários e outros serviços definidos em contratos, atos de concessão ou de permissão ou em normas oficiais."],
  ["23","Serviços de programação e comunicação visual, desenho industrial e congêneres."],
  ["2301","Serviços de programação e comunicação visual, desenho industrial e congêneres."],
  ["24","Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres."],
  ["2401","Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres."],
  ["25","Serviços funerários."],
  ["2501","Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico; fornecimento de flores, coroas e outros paramentos; desembaraço de certidão de óbito; fornecimento de véu, essa e outros adornos; embalsamento, embelezamento, conservação ou restauração de cadáveres."],
  ["2502","Translado intramunicipal e cremação de corpos e partes de corpos cadavéricos."],
  ["2503","Planos ou convênio funerários."],
  ["2504","Manutenção e conservação de jazigos e cemitérios."],
  ["2505","Cessão de uso de espaços em cemitérios para sepultamento."],
  ["26","Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres."],
  ["2601","Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres."],
  ["27","Serviços de assistência social."],
  ["2701","Serviços de assistência social."],
  ["28","Serviços de avaliação de bens e serviços de qualquer natureza."],
  ["2801","Serviços de avaliação de bens e serviços de qualquer natureza."],
  ["29","Serviços de biblioteconomia."],
  ["2901","Serviços de biblioteconomia."],
  ["30","Serviços de biologia, biotecnologia e química."],
  ["3001","Serviços de biologia, biotecnologia e química."],
  ["31","Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres."],
  ["3101","Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres."],
  ["32","Serviços de desenhos técnicos."],
  ["3201","Serviços de desenhos técnicos."],
  ["33","Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres."],
  ["3301","Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres."],
  ["34","Serviços de investigações particulares, detetives e congêneres."],
  ["3401","Serviços de investigações particulares, detetives e congêneres."],
  ["35","Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas."],
  ["3501","Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas."],
  ["36","Serviços de meteorologia."],
  ["3601","Serviços de meteorologia."],
  ["37","Serviços de artistas, atletas, modelos e manequins."],
  ["3701","Serviços de artistas, atletas, modelos e manequins."],
  ["38","Serviços de museologia."],
  ["3801","Serviços de museologia."],
  ["39","Serviços de ourivesaria e lapidação."],
  ["3901","Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço)."],
  ["40","Serviços relativos a obras de arte sob encomenda."],
  ["4001","Obras de arte sob encomenda."],
  ["99","Serviços sem a incidência de ISSQN e ICMS"],
  ["9901","Serviços sem a incidência de ISSQN e ICMS"],
];
