import { useEffect, useState } from 'react';
import { calcularGestao, contasGerenciais } from '../../../../../../packages/shared/src/analise/gestao.js';
const brl=v=>v==null?'Classificação pendente':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function BaseGerencial({api,empresaId,dre}) {
  const [base,setBase]=useState(null),[editando,setEditando]=useState(false),[rascunho,setRascunho]=useState({}),[erro,setErro]=useState(''),[salvando,setSalvando]=useState(false),[tentativa,setTentativa]=useState(0);
  useEffect(()=>{let vivo=true;setBase(null);setErro('');setEditando(false);Promise.resolve().then(()=>api.getClassificacaoGerencial(empresaId)).then(r=>{if(r.ok===false)throw Error(r.message);if(vivo){setBase(r);setRascunho(r.contas);}}).catch(e=>{if(vivo)setErro('Não foi possível carregar a classificação gerencial. '+e.message);});return()=>{vivo=false;};},[api,empresaId,tentativa]);
  const contas=contasGerenciais(dre),r=base?calcularGestao(dre,base.contas):null;
  async function salvar(){setSalvando(true);setErro('');try{const retorno=await api.salvarClassificacaoGerencial(empresaId,{contas:rascunho,revisao:base.revisao});if(retorno.ok===false)throw Error(retorno.message);setBase(retorno);setEditando(false);}catch(e){setErro(e.message)}finally{setSalvando(false)}}
  return <section className="bi-card"><h2>Estrutura de custos e pró-labore</h2><p>Classificação gerencial por conta completa, sem alterar a DRE ou os lançamentos. Tributos e deduções já classificados entram uma única vez.</p>
    {erro&&<p role="alert">{erro} <button onClick={()=>setTentativa(n=>n+1)}>Recarregar classificação</button></p>}
    {r&&<><div className="bi-cards">{[['Contribuição',brl(r.contribuicao)],['Ponto de equilíbrio',brl(r.equilibrio)],['Cobertura dos custos fixos',r.cobertura==null?'Sem base':`${r.cobertura.toFixed(2)}×`],['Pró-labore na DRE',brl(r.prolabore)]].map(([k,v])=><div key={k}><h3>{k}</h3><strong>{v}</strong></div>)}</div><p>{r.bloqueado?`${r.pendentes.length} conta(s) pendente(s). Classifique todas as contas com movimento e confira inconsistências da DRE para habilitar os indicadores.`:'Valores por competência. Pró-labore já participa do resultado; não é descontado novamente. Não comprova pagamento ou distribuição disponível.'}</p>{r.prolaborePercentual!=null&&<p>Pró-labore / receita bruta: {r.prolaborePercentual.toFixed(1)}%. Somente contas explicitamente marcadas.</p>}<button onClick={()=>{setRascunho(base.contas);setEditando(v=>!v)}}>{editando?'Cancelar edição':'Classificar contas gerenciais'}</button></>}
    {editando&&base&&<><p>Marque pró-labore apenas em contas de despesas com pessoal. Classificação salva vale para relatórios da empresa; cenários já salvos permanecem imutáveis.</p><div className="bi-scroll"><table><thead><tr><th>Conta</th><th>Valor</th><th>Comportamento</th><th>Pró-labore</th></tr></thead><tbody>{contas.map(c=><tr key={c.codigo}><td>{c.nome} · {c.codigo}<small>{c.categoria}</small></td><td>{brl(c.custo)}</td><td><select aria-label={`Comportamento ${c.codigo}`} value={rascunho[c.codigo]?.comportamento||''} onChange={e=>setRascunho(v=>{const n={...v};if(!e.target.value)delete n[c.codigo];else n[c.codigo]={prolabore:false,...n[c.codigo],comportamento:e.target.value};return n;})}><option value="">Pendente</option><option value="FIXO">Fixo</option><option value="VARIAVEL">Variável</option></select></td><td><input aria-label={`Pró-labore ${c.codigo}`} type="checkbox" disabled={!String(c.codigo).startsWith('41101')||!rascunho[c.codigo]} checked={rascunho[c.codigo]?.prolabore||false} onChange={e=>setRascunho(v=>({...v,[c.codigo]:{...v[c.codigo],prolabore:e.target.checked}}))}/></td></tr>)}</tbody></table></div><button disabled={salvando} onClick={salvar}>{salvando?'Salvando…':'Salvar classificação'}</button></>}
  </section>;
}
