import { useEffect,useState } from 'react';
import { resumirSocios } from '../../../../../../packages/shared/src/analise/socios.js';
const brl=v=>v==null?'Sem base':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function mesesEntre(de,ate){const meses=[];for(let m=de;m<=ate&&meses.length<24;){meses.push(m);const [a,b]=m.split('-').map(Number);m=new Date(Date.UTC(a,b,1)).toISOString().slice(0,7);}return meses;}
export function BaseSocios({api,empresaId,de,ate,resultado}) {
 const [dados,setDados]=useState(null),[erro,setErro]=useState(''),[edicao,setEdicao]=useState(false),[form,setForm]=useState({competencia:ate,prolaborePago:'',distribuicaoPaga:'',outrasRetiradas:'',fonte:'',confirmado:false}),[salvando,setSalvando]=useState(false),[versao,setVersao]=useState(0);
 useEffect(()=>{let vivo=true;setDados(null);setErro('');Promise.resolve().then(()=>api.getBaseSociosGerencial(empresaId,{de,ate})).then(r=>{if(r.ok===false)throw Error(r.message);if(vivo)setDados(r.registros);}).catch(e=>{if(vivo)setErro(e.message)});return()=>{vivo=false;};},[api,empresaId,de,ate,versao]);
 async function salvar(){setSalvando(true);setErro('');try{const r=await api.salvarBaseSociosGerencial(empresaId,form);if(r.ok===false)throw Error(r.message);setVersao(v=>v+1);setEdicao(false);}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 function abrir(){const anterior=dados?.find(r=>r.competencia===ate);setForm(anterior?{...anterior,confirmado:false}:{competencia:ate,prolaborePago:'',distribuicaoPaga:'',outrasRetiradas:'',fonte:'',confirmado:false});setEdicao(true);}
 const r=dados?resumirSocios(dados,mesesEntre(de,ate),resultado):null;
 return <section className="bi-card"><h2>Retiradas dos sócios · base declarada</h2><p>Informe pagamentos conferidos pelo contador, com a referência do documento ou controle utilizado. Não altera a contabilidade. Cada salvamento preserva a versão anterior.</p>{erro&&<p role="alert">{erro}</p>}{r?.completo?<><div className="bi-cards">{[['Pró-labore pago',r.prolabore],['Distribuição paga',r.distribuicao],['Outras retiradas',r.outras],['Total declarado',r.total],['Resultado do período menos distribuição',r.resultadoMenosDistribuicao]].map(([n,v])=><div key={n}><h3>{n}</h3><strong>{brl(v)}</strong></div>)}</div><p>O último valor não representa saldo bancário ou lucro disponível para distribuir. O pró-labore da DRE já foi descontado do resultado e não é descontado novamente.</p></>:r&&<p>Falta confirmação em {r.faltas.join(', ')}. Ausência de declaração não significa retirada zero.</p>}<button onClick={abrir} disabled={!dados}>Conferir pagamentos de {ate}</button>{dados?.map(d=><p key={d.id}>{d.competencia} · Fonte: {d.fonte} · Registrado em {new Date(d.createdAt).toLocaleString('pt-BR')}</p>)}
 {edicao&&<div className="bi-filtros"><label>Mês conferido<select value={form.competencia} onChange={e=>{const anterior=dados.find(r=>r.competencia===e.target.value);setForm(anterior?{...anterior,confirmado:false}:{competencia:e.target.value,prolaborePago:'',distribuicaoPaga:'',outrasRetiradas:'',fonte:'',confirmado:false});}}>{mesesEntre(de,ate).map(m=><option key={m} value={m}>{m}</option>)}</select></label>{[['prolaborePago','Pró-labore pago'],['distribuicaoPaga','Distribuição de lucros paga'],['outrasRetiradas','Outras retiradas pagas']].map(([k,l])=><label key={k}>{l}<input type="number" min="0" step=".01" value={form[k]} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>)}<label>Documento ou controle de origem<input maxLength={1000} value={form.fonte} onChange={e=>setForm(v=>({...v,fonte:e.target.value}))}/></label><label><input type="checkbox" checked={form.confirmado} onChange={e=>setForm(v=>({...v,confirmado:e.target.checked}))}/> Conferi os pagamentos; zeros também foram confirmados.</label><button disabled={salvando||!form.confirmado} onClick={salvar}>Salvar declaração de {form.competencia}</button><button disabled={salvando} onClick={()=>setEdicao(false)}>Cancelar</button></div>}
 </section>;
}
