import { useEffect, useRef, useState } from 'react';
import { calcularGestao, contasGerenciais } from '../../../../../../packages/shared/src/analise/gestao.js';
const brl=v=>v==null?'Classificação pendente':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function BaseGerencial({api,empresaId,dre}) {
  const geracao=useRef(0);
  useEffect(()=>{geracao.current++;setSalvando(false);return()=>{geracao.current++;};},[api,empresaId]);
  const [base,setBase]=useState(null),[editando,setEditando]=useState(false),[rascunho,setRascunho]=useState({}),[erro,setErro]=useState(''),[salvando,setSalvando]=useState(false),[tentativa,setTentativa]=useState(0);
  useEffect(()=>{let vivo=true;setBase(null);setErro('');setEditando(false);Promise.resolve().then(()=>api.getClassificacaoGerencial(empresaId)).then(r=>{if(r.ok===false)throw Error(r.message);if(vivo){setBase(r);setRascunho(r.contas);}}).catch(e=>{if(vivo)setErro('Não foi possível carregar a classificação gerencial. '+e.message);});return()=>{vivo=false;};},[api,empresaId,tentativa]);
  const [selecionadas,setSelecionadas]=useState([]),[filtro,setFiltro]=useState('todas');
  useEffect(()=>{setSelecionadas([]);setEditando(false);},[empresaId,dre]);
  const contas=contasGerenciais(dre),r=base?calcularGestao(dre,base.contas):null;
  const visiveis=contas.filter(c=>filtro==='todas'||!rascunho[c.codigo]);
  function aplicar(comportamento){setRascunho(v=>{const n={...v};for(const codigo of selecionadas)n[codigo]={...n[codigo],comportamento,prolabore:n[codigo]?.prolabore||false};return n;});setSelecionadas([]);}
  async function salvar(){const atual=geracao.current;setSalvando(true);setErro('');try{const retorno=await api.salvarClassificacaoGerencial(empresaId,{contas:rascunho,revisao:base.revisao});if(atual!==geracao.current)return;if(retorno.ok===false)throw Error(retorno.message);setBase(retorno);setEditando(false);}catch(e){if(atual===geracao.current)setErro(e.message)}finally{if(atual===geracao.current)setSalvando(false)}}
  return <section className="bi-card"><h2>Estrutura de custos e pró-labore</h2><p>Regras automáticas nas contas reconhecidas. Suas classificações confirmadas têm prioridade; dúvidas ficam para revisão.</p>
    {erro&&<p role="alert">{erro} <button onClick={()=>setTentativa(n=>n+1)}>Recarregar classificação</button></p>}
    {r&&<>{r.automaticas.length>0&&<p role="status">{r.automaticas.length} conta(s) classificada(s) automaticamente por regra. Você pode revisar e alterar.</p>}<div className="bi-cards">{[['Contribuição',brl(r.contribuicao)],['Ponto de equilíbrio',brl(r.equilibrio)],['Cobertura dos custos fixos',r.cobertura==null?'Sem base':`${r.cobertura.toFixed(2)}×`],['Pró-labore na DRE',brl(r.prolabore)]].map(([k,v])=><div key={k}><h3>{k}</h3><strong>{v}</strong></div>)}</div><p>{r.bloqueado?`${r.pendentes.length} conta(s) pendente(s). Classifique as contas abaixo e confira as pendências da base para habilitar os indicadores.`:'Valores por competência. Pró-labore já participa do resultado; não é descontado novamente. Não comprova pagamento ou distribuição disponível.'}</p>{r.pendentes.length>0&&<details><summary>Contas que faltam classificar ({r.pendentes.length})</summary><ul>{contas.filter(c=>r.pendentes.includes(c.codigo)).map(c=><li key={c.codigo}>{c.nome} · {c.codigo} · {brl(c.custo)}</li>)}</ul></details>}{contas.some(c=>c.custo<0)&&<p className="bi-aviso">Há contas com saldo credor ou estorno. Confira os lançamentos antes de interpretar contribuição e ponto de equilíbrio.</p>}{r.prolaborePercentual!=null&&<p>Pró-labore / receita bruta: {r.prolaborePercentual.toFixed(1)}%. Somente contas explicitamente marcadas.</p>}<button disabled={salvando} onClick={()=>{setSelecionadas([]);setFiltro('todas');setRascunho(r.classificacoes);setEditando(v=>!v)}}>{editando?'Cancelar edição':'Classificar contas gerenciais'}</button> <button disabled={salvando} onClick={()=>{setSelecionadas([]);setFiltro('todas');setRascunho({...r.classificacoes,...Object.fromEntries(Object.entries(r.sugestoes).map(([codigo,s])=>[codigo,{comportamento:s.comportamento,prolabore:s.prolabore}]))});setEditando(true);}}>Revisar sugestões em lote</button></>}
    {editando&&base&&<><p>Marque pró-labore apenas em contas de despesas com pessoal. Classificação salva vale para relatórios da empresa; cenários já salvos permanecem imutáveis.</p><div className="bi-acoes bi-revisao-acoes"><label>Exibir <select aria-label="Filtrar contas" value={filtro} disabled={salvando} onChange={e=>{setFiltro(e.target.value);setSelecionadas([]);}}><option value="todas">Todas as contas</option><option value="pendentes">Sem classificação no rascunho</option></select></label><span role="status">{selecionadas.length} selecionada(s)</span><button disabled={salvando||!selecionadas.length} onClick={()=>aplicar('FIXO')}>Aplicar fixo</button><button disabled={salvando||!selecionadas.length} onClick={()=>aplicar('VARIAVEL')}>Aplicar variável</button></div><fieldset disabled={salvando} className="bi-revisao-campos"><legend className="bi-sr-only">Revisão de contas</legend><div className="bi-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Selecionar contas visíveis" checked={visiveis.length>0&&visiveis.every(c=>selecionadas.includes(c.codigo))} onChange={e=>setSelecionadas(e.target.checked?visiveis.map(c=>c.codigo):[])}/></th><th>Conta</th><th>Valor</th><th>Comportamento</th><th>Pró-labore</th><th>Origem</th></tr></thead><tbody>{visiveis.map(c=><tr key={c.codigo}><td><input type="checkbox" aria-label={`Selecionar ${c.nome} ${c.codigo}`} checked={selecionadas.includes(c.codigo)} onChange={e=>setSelecionadas(v=>e.target.checked?[...v,c.codigo]:v.filter(x=>x!==c.codigo))}/></td><td>{c.nome} · {c.codigo}<small>{c.categoria}</small></td><td>{brl(c.custo)}</td><td><select aria-label={`Comportamento ${c.codigo}`} value={rascunho[c.codigo]?.comportamento||''} onChange={e=>setRascunho(v=>{const n={...v};if(!e.target.value)delete n[c.codigo];else n[c.codigo]={prolabore:false,...n[c.codigo],comportamento:e.target.value};return n;})}><option value="">Pendente</option><option value="FIXO">Fixo</option><option value="VARIAVEL">Variável</option></select></td><td><input aria-label={`Pró-labore ${c.codigo}`} type="checkbox" disabled={!String(c.codigo).startsWith('41101')||!rascunho[c.codigo]} checked={rascunho[c.codigo]?.prolabore||false} onChange={e=>setRascunho(v=>({...v,[c.codigo]:{...v[c.codigo],prolabore:e.target.checked}}))}/></td><td>{base.contas[c.codigo]?'Confirmada pelo contador':r.sugestoes[c.codigo]?<><strong style={{fontSize:'.8rem'}}>{r.sugestoes[c.codigo].confianca==='ALTA'?'Regra automática':'Sugestão para conferir'}</strong><p>{r.sugestoes[c.codigo].motivo}</p></>:'Sem regra segura — classifique manualmente'}</td></tr>)}</tbody></table></div></fieldset>{!visiveis.length&&<p>Nenhuma conta neste filtro.</p>}<p>As alterações só são confirmadas ao salvar. Contas fora deste período são preservadas.</p><button disabled={salvando} onClick={salvar}>{salvando?'Salvando…':'Salvar classificação'}</button></>}
  </section>;
}
