import { calcularGestao } from '../../../../../../packages/shared/src/analise/gestao.js';
import { useEffect, useRef, useState } from 'react';
import { createPortal, flushSync } from 'react-dom';
import './imprimirRelatorio.css';
const brl=v=>v==null?'Sem base':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function ImprimirRelatorio({api,empresaId,empresaNome,empresaCnpj,dados,de,ate,comparar}) {
  const ativo=useRef(true);
  useEffect(()=>{ativo.current=true;return()=>{ativo.current=false;};},[]);
  const [foto,setFoto]=useState(null),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false);
  async function imprimir(){setOcupado(true);setErro('');try{
    const snapshot=await api.getRelatorioGerencialSnapshot(empresaId,{de,ate,comparar});if(snapshot.ok===false)throw Error(snapshot.message);
    const {dados,clientes,classificacao}=snapshot;
    if(!ativo.current)return;
    flushSync(()=>setFoto(JSON.parse(JSON.stringify({dados,clientes,socios:snapshot.socios,basesSocios:snapshot.basesSocios||[],gestao:calcularGestao(dados.atual.dre,classificacao),nome:snapshot.empresa?.razao||empresaNome||empresaId,cnpj:snapshot.empresa?.cnpj||empresaCnpj,gerado:new Date().toLocaleString('pt-BR')}))));
    document.body.classList.add('imprimindo-gerencial');
    const limpar=()=>{document.body.classList.remove('imprimindo-gerencial');setFoto(null);};
    window.addEventListener('afterprint',limpar,{once:true});
    try{window.print()}finally{window.removeEventListener('afterprint',limpar);limpar();}
  }catch(e){setErro(e.message||'Não foi possível preparar o relatório completo.')}finally{setOcupado(false)}}
  return <><button disabled={ocupado} onClick={imprimir}>{ocupado?'Preparando relatório…':'Imprimir relatório completo'}</button>{erro&&<p role="alert">{erro}</p>}{foto&&createPortal(<article id="relatorio-gerencial-impressao"><header><h1>Relatório gerencial</h1><h2>{foto.nome}</h2>{foto.cnpj&&<p>CNPJ: {foto.cnpj}</p>}<p>{de} a {ate} · Comparação: {foto.dados.anterior.de} a {foto.dados.anterior.ate}</p><p>Gerado em {foto.gerado} · {foto.dados.demonstracao?'DEMONSTRAÇÃO — DADOS FICTÍCIOS':'Uso consultivo do escritório'}</p></header>
    <section><h2>Visão geral</h2><p>{foto.dados.atual.parcial||foto.dados.anterior.parcial?'BASE PARCIAL: competências sem registros ou ainda não conferidas.':'Histórico observado; conferir fechamento antes de concluir.'}</p><table><thead><tr><th>Indicador</th><th>Atual</th><th>Anterior</th></tr></thead><tbody>{[['Faturamento documental','faturamento'],['Resultado da DRE','resultado'],['Despesas','despesas'],['Guias correntes','tributos']].map(([n,k])=><tr key={k}><th>{n}</th><td>{brl(foto.dados.atual.indicadores[k])}</td><td>{brl(foto.dados.anterior.indicadores[k])}</td></tr>)}</tbody></table>{foto.dados.insights.map((i,n)=><p key={n}>{i.texto}</p>)}</section>
    <section><h2>Resultado por competência</h2><p>DRE gerencial; não é peça fiscal nem demonstração de caixa.</p><table><thead><tr><th>Linha da DRE</th><th>Atual</th><th>Anterior</th></tr></thead><tbody>{foto.dados.atual.dre.linhas.map(l=><tr key={l.chave}><th>{l.rotulo}</th><td>{brl(foto.dados.atual.dre.semLancamento?null:l.valor)}</td><td>{brl(foto.dados.anterior.dre.semLancamento?null:foto.dados.anterior.dre.linhas.find(a=>a.chave===l.chave)?.valor)}</td></tr>)}</tbody></table></section>
    <section><h2>Evolução mensal</h2><svg viewBox="0 0 640 140" role="img" aria-label="Evolução do faturamento documental">{foto.dados.serie.slice(-12).map((m,i)=>{const altura=Math.max(0,m.indicadores.faturamento||0)/Math.max(1,...foto.dados.serie.map(s=>s.indicadores.faturamento||0))*95;return <g key={m.competencia}><rect x={i*52+4} y={110-altura} width="35" height={altura} fill="#75609c"/><text x={i*52+4} y="128" fontSize="9">{m.competencia}</text></g>})}</svg><table><thead><tr><th>Mês</th><th>Faturamento</th><th>Resultado</th></tr></thead><tbody>{foto.dados.serie.map(m=><tr key={m.competencia}><td>{m.competencia}</td><td>{brl(m.indicadores.faturamento)}</td><td>{brl(m.indicadores.resultado)}</td></tr>)}</tbody></table></section>
    <section><h2>Estrutura de custos</h2>{foto.gestao.automaticas?.length>0&&<p>{foto.gestao.automaticas.length} conta(s) por regra automática, revisável pelo contador.</p>}<p>{foto.gestao.bloqueado?'Classificação incompleta ou inconsistências: indicadores de contribuição e equilíbrio indisponíveis.':<>Contribuição: {brl(foto.gestao.contribuicao)} · Ponto de equilíbrio: {brl(foto.gestao.equilibrio)} · Pró-labore já incluído no resultado: {brl(foto.gestao.prolabore)}.</>}</p></section>
    <section><h2>Clientes — todos os períodos comparados</h2><p>Notas autorizadas, identificadas por CPF/CNPJ. Ausência de emissão não comprova perda contratual. {foto.clientes.semIdentificacao} documento(s) sem identificação: {brl(foto.clientes.valorSemIdentificacao)} fora da carteira.</p><table><thead><tr><th>Cliente / documento</th><th>Atual</th><th>Anterior</th><th>Acumulado observado</th></tr></thead><tbody>{foto.clientes.clientes.filter(c=>c.atual>0||c.anterior>0).map(c=><tr key={c.documento}><td>{c.nome}<br/>{c.documento}</td><td>{brl(c.atual)}</td><td>{brl(c.anterior)}</td><td>{brl(c.acumulado)}</td></tr>)}</tbody></table></section>
    <section><h2>Retiradas declaradas pelo contador</h2>{foto.socios?.completo?<p>Pró-labore pago: {brl(foto.socios.prolabore)} · Distribuição paga: {brl(foto.socios.distribuicao)} · Outras retiradas: {brl(foto.socios.outras)} · Total: {brl(foto.socios.total)}.</p>:<p>Sem base confirmada para todo o período; ausência não significa retirada zero.</p>}{foto.basesSocios.map(r=><p key={r.id}>{r.competencia} · Fonte: {r.fonte}</p>)}</section>
    <section><h2>Guias da competência</h2><p>Parcelamentos destacados; situação atual não comprova pagamento no período.</p><table><thead><tr><th>Guia</th><th>Competência</th><th>Valor</th><th>Situação</th></tr></thead><tbody>{foto.dados.guias.filter(g=>g.competencia>=de&&g.competencia<=ate).map(g=><tr key={g.id}><td>{g.tipo}{g.parcelamentoId?' (parcelamento)':''}</td><td>{g.competencia}</td><td>{brl(g.valor)}</td><td>{g.paymentStatus==='PAID'?'Paga':g.paymentStatus==='OVERDUE'?'Em atraso':'Em aberto'}</td></tr>)}</tbody></table></section>
    <footer><h2>Cobertura e fontes</h2><table><thead><tr><th>Mês</th><th>Contabilidade</th><th>Faturamento</th><th>Guias correntes</th></tr></thead><tbody>{foto.dados.cobertura.map(m=><tr key={m.competencia}><td>{m.competencia}</td><td>{m.fechadoContabilEm?'Fechamento registrado':m.contabilidade?'Com registros':'Sem registros'}</td><td>{m.semFaturamentoConfirmado?'Zero confirmado':m.faturamento?'Com registros':'Sem registros'}</td><td>{m.guias?'Com registros':'Sem registros'}</td></tr>)}</tbody></table>{foto.dados.avisos.map((a,i)=><p key={i}>{a}</p>)}<p>Fontes: lançamentos e plano de contas, notas autorizadas e guias processadas. Não representa saldo bancário, recebimento, previsão contratual ou autorização de distribuição.</p></footer>
  </article>,document.body)}</>;
}
