import { ajustarReceita } from '../../../../../../packages/shared/src/analise/classificacao.js';
import { useEffect, useRef, useState } from 'react';
import { calcularCenario, calcularMeta, receitaParaMargem, calcularGestao } from '../../../../../../packages/shared/src/analise/gestao.js';
import './analiseEmpresa.css';
const moeda=v=>v==null?'Sem base':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const vazio={receita:'',fixos:'',variaveis:'',prolabore:'',clientes:'',aliquota:'',tributosNosCustos:false,outrasReceitas:0};
const rotulos={receita:'Faturamento mensal',fixos:'Custos fixos',variaveis:'Custos variáveis',prolabore:'Pró-labore separado',clientes:'Clientes com faturamento',aliquota:'Tributo sobre receita (%) — premissa',outrasReceitas:'Outras receitas mensais (opcional)'};
const indicadores={receita:'Faturamento',tributos:'Tributos estimados',contribuicao:'Margem de contribuição (R$)',resultado:'Resultado estimado',margem:'Margem estimada (%)',ticket:'Faturamento por cliente',equilibrio:'Ponto de equilíbrio'};
function avaliar(p){try{return {dados:calcularCenario(p)}}catch(e){return {erro:e.message}}}
export function LaboratorioEmpresa({api,empresas=[],onVoltar,onTributario}) {
  const [companyId,setCompanyId]=useState(''),[nome,setNome]=useState('Meu cenário'),[periodo,setPeriodo]=useState(()=>new Date().toISOString().slice(0,7));
  const [a,setA]=useState({...vazio}),[b,setB]=useState({...vazio}),[meta,setMeta]=useState(''),[salvos,setSalvos]=useState([]),[mensagem,setMensagem]=useState(''),[ocupado,setOcupado]=useState(false),[apresentar,setApresentar]=useState(false),[fonte,setFonte]=useState('Premissas manuais.');
  const [acao,setAcao]=useState('ganhar'),[impacto,setImpacto]=useState('');
  const contexto=useRef(0), baseEdicao=useRef({});
  const ra=avaliar(a),rb=avaliar(b),objetivo=rb.dados&&meta!==''?calcularMeta(b,Number(meta)):null;
  useEffect(()=>{let vivo=true;api.listarCenariosLaboratorio().then(r=>{if(r.ok===false)throw Error(r.message);if(vivo)setSalvos(r.cenarios);}).catch(e=>{if(vivo)setMensagem(e.message)});return()=>{vivo=false;contexto.current++;};},[api]);
  function trocar(id){contexto.current++;setCompanyId(id);setA({...vazio});setB({...vazio});setMensagem('');setFonte('Premissas manuais.');setApresentar(false);}
  async function carregar(){const versao=++contexto.current;setOcupado(true);setMensagem('');try{
    const snapshot=await api.getRelatorioGerencialSnapshot(companyId,{de:periodo,ate:periodo,comparar:'anterior'});
    if(snapshot.ok===false)throw Error(snapshot.message);
    const r=snapshot.dados;
    if(r.ok===false)throw Error(r.message);
    if(contexto.current!==versao)return;
    const receita=r.atual.dre.semLancamento?null:r.atual.dre.linhas.find(l=>l.chave==='receitaBruta')?.valor;
    const gestao=calcularGestao(r.atual.dre,snapshot.classificacao);
    const prolaboreVariavel=Object.values(gestao.classificacoes).some(c=>c.prolabore&&c.comportamento==='VARIAVEL');
    const completos=!gestao.bloqueado&&!prolaboreVariavel;
    const outrasReceitas=r.atual.dre.semLancamento?0:r.atual.dre.linhas.filter(l=>['receitasFinanceiras','outrasReceitas'].includes(l.chave)).reduce((s,l)=>s+l.valor,0);
    const premissas={...vazio,outrasReceitas,receita:receita??r.atual.indicadores.faturamento??'',clientes:snapshot.clientes.resumo.ativos||'',...(completos?{fixos:Math.max(0,gestao.fixos-gestao.prolabore),variaveis:gestao.variaveis,prolabore:gestao.prolabore,aliquota:0,tributosNosCustos:true}:{})};
    setA(premissas);setB({...premissas});
    setFonte('Foto de '+periodo+'. '+(completos?'Receita e custos da DRE classificados; tributos e deduções permanecem incluídos nos custos. Clientes vêm de notas identificadas.':'Classificação insuficiente: complete custos, pró-labore e alíquota. Receita usa DRE quando disponível, senão documentos.')+(r.atual.parcial?' Base parcial: confira antes de usar.':'')+(gestao.automaticas.length?' '+gestao.automaticas.length+' conta(s) por regra automática; revise a classificação no relatório.':'')+' Premissas podem ser ajustadas; não altera a empresa.');
  }catch(e){if(contexto.current===versao)setMensagem(e.message)}finally{setOcupado(false)}}
  async function salvar(){setOcupado(true);setMensagem('');try{const r=await api.salvarCenarioLaboratorio({nome,periodo,companyId:companyId||null,a,b,procedencia:fonte});if(r.ok===false)throw Error(r.message);setSalvos(s=>[r.cenario,...s].slice(0,100));setMensagem('Nova versão salva. Os dados da empresa não foram alterados.');}catch(e){setMensagem(e.message)}finally{setOcupado(false)}}
  function abrir(c){contexto.current++;setCompanyId(c.companyId||'');setNome(c.nome);setPeriodo(c.periodo);setA(c.entradasJson.a);setB(c.entradasJson.b);setApresentar(false);setFonte(`Foto salva em ${new Date(c.createdAt).toLocaleString('pt-BR')}. Fórmula ${c.versao}. ${c.origemJson?.declaracaoAutor||'Premissas do autor.'} Sem atualização automática.`);setMensagem('');}
  function aplicarDecisao(){const v=Number(impacto);if(impacto===''||!Number.isFinite(v)||v<0){setMensagem('Informe um valor positivo para o impacto mensal.');return;}if(acao==='perder'&&(v>Number(b.receita)||Number(b.clientes)<1)){setMensagem('A perda deve caber no faturamento e na quantidade de clientes de B.');return;}setB(p=>({...p,...(acao==='ganhar'||acao==='perder'?{...ajustarReceita(p,Math.max(0,Number(p.receita)+(acao==='ganhar'?v:-v))),clientes:Math.max(0,Number(p.clientes)+(acao==='ganhar'?1:-1))}:acao==='prolabore'?{prolabore:Number(p.prolabore)+v}:{fixos:Number(p.fixos)+v})}));setMensagem('Premissa aplicada a B. Custos variáveis acompanham proporcionalmente a receita quando há base positiva. Confira as premissas.');}
  function modelo(){setA({receita:20000,fixos:5000,variaveis:2000,prolabore:3000,clientes:40,aliquota:''});setB({receita:20000,fixos:5000,variaveis:2000,prolabore:3000,clientes:40,aliquota:''});setNome('Prestador de serviços — exemplo fictício');setFonte('Exemplo didático fictício, não representa média de mercado. Informe a premissa tributária.');}
  function decisao(tipo){setB(v=>{const next={...v};if(tipo==='preco')return ajustarReceita(v,Math.round(Number(v.receita)*1.1*100)/100);if(tipo==='contratar')next.fixos=Number(v.fixos)+3000;return next});setMensagem(tipo==='preco'?'Premissa aplicada: receita +10%, custos fixos preservados e variáveis proporcionais. Confira a relação com o preço.':'Premissa aplicada: custo total mensal de contratação de R$ 3.000. Ajuste para o custo efetivo desejado.');}
  return <main className="analise-empresa laboratorio-empresa" style={{maxWidth:1400,margin:'auto',padding:24}}>
    <header><div className="bi-atalhos">{onVoltar&&<button onClick={onVoltar}>Voltar</button>}{onTributario&&<button onClick={onTributario}>Simulação tributária</button>}<button disabled={!!companyId} onClick={()=>setApresentar(v=>!v)}>{apresentar?'Encerrar apresentação':'Modo apresentação fictícia'}</button></div><h1>Laboratório da Empresa</h1><p>{companyId?'Empresa existente · simulação com premissas':'Empresa fictícia · sem cadastro ou emissão fiscal'}</p></header>
    {!apresentar&&<><section className="bi-card bi-filtros"><label>Base<select aria-label="Base do cenário" disabled={ocupado} value={companyId} onChange={e=>trocar(e.target.value)}><option value="">Empresa fictícia</option>{empresas.filter(e=>e.companyId||e.id).map(e=><option key={e.companyId||e.id} value={e.companyId||e.id}>{e.razaoSocial||e.razao||e.nome||e.id}</option>)}</select></label><label>Nome do cenário<input maxLength={120} value={nome} onChange={e=>setNome(e.target.value)}/></label><label>Mês de referência<input disabled={ocupado} type="month" value={periodo} onChange={e=>{contexto.current++;setPeriodo(e.target.value);}}/></label>{!companyId&&<button onClick={modelo}>Usar exemplo fictício</button>}{companyId&&<button disabled={ocupado||!periodo} onClick={carregar}>Trazer base do mês</button>}</section><p>{fonte}</p><details className="bi-metodologia"><summary>Como preencher as premissas</summary><p>Fixos e variáveis devem excluir o pró-labore separado. Se os custos já incluem tributos, marque essa opção para não calculá-los novamente. A alíquota é uma premissa explícita, não uma apuração fiscal. Custos fixos permanecem mesmo com perda de cliente. Ao alterar receita, os custos variáveis acompanham sua proporção; revise se o contrato funcionar de outra forma.</p></details></>}
    <h2>{nome} · Cenário A × Cenário B</h2>
    <div className="bi-cards">{[[a,setA,'Cenário A'],[b,setB,'Cenário B']].map(([p,set,titulo])=><section className="bi-card" key={titulo}><h2>{titulo}</h2><div className="bi-filtros">{Object.entries(rotulos).map(([k,l])=><label key={k}>{l}<input disabled={k==='aliquota'&&p.tributosNosCustos} type="number" min="0" max={k==='aliquota'?100:undefined} step={k==='clientes'?1:.01} value={p[k]??0} onFocus={()=>{if(k==='receita')baseEdicao.current[titulo]={...p};}} onChange={e=>set(v=>k==='receita'?ajustarReceita({...v,receita:baseEdicao.current[titulo]?.receita??v.receita,variaveis:baseEdicao.current[titulo]?.variaveis??v.variaveis},e.target.value):({...v,[k]:e.target.value}))}/></label>)}</div><label><input type="checkbox" checked={!!p.tributosNosCustos} onChange={e=>set(v=>({...v,tributosNosCustos:e.target.checked,aliquota:e.target.checked?0:''}))}/> Tributos já incluídos nos custos</label></section>)}</div>
    {!apresentar&&<div className="bi-atalhos"><button onClick={()=>setB({...a})}>Copiar A para B</button><button disabled={!rb.dados} onClick={()=>decisao('preco')}>Testar preço +10% em B</button><button disabled={!rb.dados} onClick={()=>decisao('contratar')}>Testar contratação em B</button></div>}
    {!apresentar&&<section className="bi-card bi-filtros"><label>Decisão em B<select value={acao} onChange={e=>setAcao(e.target.value)}><option value="ganhar">Ganhar um cliente</option><option value="perder">Perder um cliente</option><option value="fixos">Aumentar custo fixo</option><option value="prolabore">Aumentar pró-labore</option></select></label><label>Impacto mensal (R$)<input type="number" min="0" value={impacto} onChange={e=>setImpacto(e.target.value)}/></label><button disabled={!rb.dados} onClick={aplicarDecisao}>Aplicar decisão em B</button></section>}
    {(ra.erro||rb.erro)&&<p role="status">Complete os dois cenários para comparar. {ra.erro||rb.erro}</p>}
    {ra.dados&&rb.dados&&<section className="bi-card"><h2>Impacto da decisão</h2><div className="bi-scroll"><table><thead><tr><th>Indicador</th><th>A</th><th>B</th><th>Diferença B − A</th></tr></thead><tbody>{Object.entries(indicadores).map(([k,l])=><tr key={k}><th>{l}</th><td>{k==='tributos'&&ra.dados.tributosNosCustos?'Incluídos nos custos':k==='margem'?ra.dados[k]?.toFixed(1)??'Sem base':moeda(ra.dados[k])}</td><td>{k==='tributos'&&rb.dados.tributosNosCustos?'Incluídos nos custos':k==='margem'?rb.dados[k]?.toFixed(1)??'Sem base':moeda(rb.dados[k])}</td><td>{ra.dados[k]==null||rb.dados[k]==null?'Sem base':k==='margem'?`${(rb.dados[k]-ra.dados[k]).toFixed(1)} p.p.`:moeda(rb.dados[k]-ra.dados[k])}</td></tr>)}</tbody></table></div><p>Para manter em B a margem de A: <strong>{moeda(receitaParaMargem(b,ra.dados.margem))}</strong> de receita mensal, mantendo proporção variável e alíquota de B. Sem base quando a margem não é alcançável com essas premissas.</p><details className="bi-metodologia"><summary>Premissas dos cálculos</summary><p>Ponto de equilíbrio operacional exige contribuição positiva e não depende de outras receitas. As metas mantêm outras receitas no valor informado. Resultado é econômico, não saldo disponível para retirada.</p></details><figure aria-label="Resultado dos cenários"><figcaption>Resultado estimado</figcaption>{[['A',ra.dados.resultado],['B',rb.dados.resultado]].map(([l,v])=><div key={l}>{l}: {moeda(v)}<div style={{height:16,background:v<0?'#ed997b':'#ab8de8',width:`${Math.abs(v)/Math.max(1,Math.abs(ra.dados.resultado),Math.abs(rb.dados.resultado))*100}%`}}/></div>)}</figure></section>}
    <section className="bi-card"><h2>Quanto preciso faturar?</h2><label>Meta mensal de resultado em B<input type="number" min="0" value={meta} onChange={e=>setMeta(e.target.value)}/></label>{objetivo?<p>Faturamento estimado: <strong>{moeda(objetivo.receita)}</strong> · {objetivo.clientes??'Sem base de'} clientes, mantendo ticket e proporção de custos variáveis de B.</p>:<p>Informe a meta e uma base com receita e contribuição positivas.</p>}</section>
    {!apresentar&&<section className="bi-card"><button className="bi-primary" disabled={ocupado||!ra.dados||!rb.dados||!nome.trim()} onClick={salvar}>{ocupado?'Aguarde…':'Salvar nova versão'}</button><p role="status">{mensagem}</p><h2>Minhas versões salvas</h2>{!salvos.length&&<p>Nenhum cenário salvo.</p>}{salvos.map(c=><p key={c.id}><button disabled={ocupado} onClick={()=>abrir(c)}>{c.nome} · {c.periodo} · {new Date(c.createdAt).toLocaleString('pt-BR')}</button></p>)}</section>}
  </main>;
}
