// GERADO POR `apps/api/scripts/gerar-lista-lc116.mjs` — NÃO EDITAR À MÃO.
//
// Lista de serviços anexa à Lei Complementar nº 116, de 31 de julho de 2003, já com as alterações
// da LC 157/2016. Extraída do texto compilado oficial do Planalto, versionado em `docs/lc116/`.
//
//   fonte    docs/lc116/lcp116.htm
//   SHA-256  1de1de107d8957a9314b9418d1f158e5ebb25ec5b452694d615290f2853801e2
//   medido   40 itens · 205 subitens (5 vetados);
//            8 subitens vinham em DUAS redações e a da LC 157/2016 venceu
//
// ⚠⚠ ISTO NÃO É O `cTribNac` DA NFS-e. O código de tributação nacional tem SEIS dígitos
// (item + subitem + desdobro nacional) e mora em `apps/web/src/lib/servicosNacionais/`; o item da
// LC 116 tem quatro (N.NN). Trocar um pelo outro dá granularidade errada, e o erro sai como nota
// emitida com o serviço errado — silenciosamente.
//
// ⚠ `vetado: true` é DADO. Os cinco vetados deixam buracos na numeração (3.01, 7.14, 7.15, 13.01
// e 17.07); omiti-los faria o próximo leitor achar que a extração falhou.

/** Os 40 itens — o "capítulo" do serviço. */
export const ITENS_LC116 = Object.freeze({
  1: "Serviços de informática e congêneres.",
  2: "Serviços de pesquisas e desenvolvimento de qualquer natureza.",
  3: "Serviços prestados mediante locação, cessão de direito de uso e congêneres.",
  4: "Serviços de saúde, assistência médica e congêneres.",
  5: "Serviços de medicina e assistência veterinária e congêneres.",
  6: "Serviços de cuidados pessoais, estética, atividades físicas e congêneres.",
  7: "Serviços relativos a engenharia, arquitetura, geologia, urbanismo, construção civil, manutenção, limpeza, meio ambiente, saneamento e congêneres.",
  8: "Serviços de educação, ensino, orientação pedagógica e educacional, instrução, treinamento e avaliação pessoal de qualquer grau ou natureza.",
  9: "Serviços relativos a hospedagem, turismo, viagens e congêneres.",
  10: "Serviços de intermediação e congêneres.",
  11: "Serviços de guarda, estacionamento, armazenamento, vigilância e congêneres.",
  12: "Serviços de diversões, lazer, entretenimento e congêneres.",
  13: "Serviços relativos a fonografia, fotografia, cinematografia e reprografia.",
  14: "Serviços relativos a bens de terceiros.",
  15: "Serviços relacionados ao setor bancário ou financeiro, inclusive aqueles prestados por instituições financeiras autorizadas a funcionar pela União ou por quem de direito.",
  16: "Serviços de transporte de natureza municipal.",
  17: "Serviços de apoio técnico, administrativo, jurídico, contábil, comercial e congêneres.",
  18: "Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros; prevenção e gerência de riscos seguráveis e congêneres.",
  19: "Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres.",
  20: "Serviços portuários, aeroportuários, ferroportuários, de terminais rodoviários, ferroviários e metroviários.",
  21: "Serviços de registros públicos, cartorários e notariais.",
  22: "Serviços de exploração de rodovia.",
  23: "Serviços de programação e comunicação visual, desenho industrial e congêneres.",
  24: "Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners , adesivos e congêneres.",
  25: "Serviços funerários.",
  26: "Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres.",
  27: "Serviços de assistência social.",
  28: "Serviços de avaliação de bens e serviços de qualquer natureza.",
  29: "Serviços de biblioteconomia.",
  30: "Serviços de biologia, biotecnologia e química.",
  31: "Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres.",
  32: "Serviços de desenhos técnicos.",
  33: "Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres.",
  34: "Serviços de investigações particulares, detetives e congêneres.",
  35: "Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas.",
  36: "Serviços de meteorologia.",
  37: "Serviços de artistas, atletas, modelos e manequins.",
  38: "Serviços de museologia.",
  39: "Serviços de ourivesaria e lapidação.",
  40: "Serviços relativos a obras de arte sob encomenda.",
});

/** Os 205 subitens, na ordem da lei. */
export const SUBITENS_LC116 = Object.freeze([
  {"codigo":"1.01","item":1,"subitem":"01","vetado":false,"descricao":"Análise e desenvolvimento de sistemas."},
  {"codigo":"1.02","item":1,"subitem":"02","vetado":false,"descricao":"Programação."},
  {"codigo":"1.03","item":1,"subitem":"03","vetado":false,"descricao":"Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres."},
  {"codigo":"1.04","item":1,"subitem":"04","vetado":false,"descricao":"Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets , smartphones e congêneres."},
  {"codigo":"1.05","item":1,"subitem":"05","vetado":false,"descricao":"Licenciamento ou cessão de direito de uso de programas de computação."},
  {"codigo":"1.06","item":1,"subitem":"06","vetado":false,"descricao":"Assessoria e consultoria em informática."},
  {"codigo":"1.07","item":1,"subitem":"07","vetado":false,"descricao":"Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados."},
  {"codigo":"1.08","item":1,"subitem":"08","vetado":false,"descricao":"Planejamento, confecção, manutenção e atualização de páginas eletrônicas."},
  {"codigo":"1.09","item":1,"subitem":"09","vetado":false,"descricao":"Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet, respeitada a imunidade de livros, jornais e periódicos (exceto a distribuição de conteúdos pelas prestadoras de Serviço de Acesso Condicionado, de que trata a Lei n o 12.485, de 12 de setembro de 2011 , sujeita ao ICMS)."},
  {"codigo":"2.01","item":2,"subitem":"01","vetado":false,"descricao":"Serviços de pesquisas e desenvolvimento de qualquer natureza."},
  {"codigo":"3.01","item":3,"subitem":"01","vetado":true,"descricao":null},
  {"codigo":"3.02","item":3,"subitem":"02","vetado":false,"descricao":"Cessão de direito de uso de marcas e de sinais de propaganda."},
  {"codigo":"3.03","item":3,"subitem":"03","vetado":false,"descricao":"Exploração de salões de festas, centro de convenções, escritórios virtuais, stands , quadras esportivas, estádios, ginásios, auditórios, casas de espetáculos, parques de diversões, canchas e congêneres, para realização de eventos ou negócios de qualquer natureza."},
  {"codigo":"3.04","item":3,"subitem":"04","vetado":false,"descricao":"Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza."},
  {"codigo":"3.05","item":3,"subitem":"05","vetado":false,"descricao":"Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário."},
  {"codigo":"4.01","item":4,"subitem":"01","vetado":false,"descricao":"Medicina e biomedicina."},
  {"codigo":"4.02","item":4,"subitem":"02","vetado":false,"descricao":"Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres."},
  {"codigo":"4.03","item":4,"subitem":"03","vetado":false,"descricao":"Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres."},
  {"codigo":"4.04","item":4,"subitem":"04","vetado":false,"descricao":"Instrumentação cirúrgica."},
  {"codigo":"4.05","item":4,"subitem":"05","vetado":false,"descricao":"Acupuntura."},
  {"codigo":"4.06","item":4,"subitem":"06","vetado":false,"descricao":"Enfermagem, inclusive serviços auxiliares."},
  {"codigo":"4.07","item":4,"subitem":"07","vetado":false,"descricao":"Serviços farmacêuticos."},
  {"codigo":"4.08","item":4,"subitem":"08","vetado":false,"descricao":"Terapia ocupacional, fisioterapia e fonoaudiologia."},
  {"codigo":"4.09","item":4,"subitem":"09","vetado":false,"descricao":"Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental."},
  {"codigo":"4.10","item":4,"subitem":"10","vetado":false,"descricao":"Nutrição."},
  {"codigo":"4.11","item":4,"subitem":"11","vetado":false,"descricao":"Obstetrícia."},
  {"codigo":"4.12","item":4,"subitem":"12","vetado":false,"descricao":"Odontologia."},
  {"codigo":"4.13","item":4,"subitem":"13","vetado":false,"descricao":"Ortóptica."},
  {"codigo":"4.14","item":4,"subitem":"14","vetado":false,"descricao":"Próteses sob encomenda."},
  {"codigo":"4.15","item":4,"subitem":"15","vetado":false,"descricao":"Psicanálise."},
  {"codigo":"4.16","item":4,"subitem":"16","vetado":false,"descricao":"Psicologia."},
  {"codigo":"4.17","item":4,"subitem":"17","vetado":false,"descricao":"Casas de repouso e de recuperação, creches, asilos e congêneres."},
  {"codigo":"4.18","item":4,"subitem":"18","vetado":false,"descricao":"Inseminação artificial, fertilização in vitro e congêneres."},
  {"codigo":"4.19","item":4,"subitem":"19","vetado":false,"descricao":"Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres."},
  {"codigo":"4.20","item":4,"subitem":"20","vetado":false,"descricao":"Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."},
  {"codigo":"4.21","item":4,"subitem":"21","vetado":false,"descricao":"Unidade de atendimento, assistência ou tratamento móvel e congêneres."},
  {"codigo":"4.22","item":4,"subitem":"22","vetado":false,"descricao":"Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres. (Vide Lei Complementar nº 175, de 2020)"},
  {"codigo":"4.23","item":4,"subitem":"23","vetado":false,"descricao":"Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário. (Vide Lei Complementar nº 175, de 2020)"},
  {"codigo":"5.01","item":5,"subitem":"01","vetado":false,"descricao":"Medicina veterinária e zootecnia."},
  {"codigo":"5.02","item":5,"subitem":"02","vetado":false,"descricao":"Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária."},
  {"codigo":"5.03","item":5,"subitem":"03","vetado":false,"descricao":"Laboratórios de análise na área veterinária."},
  {"codigo":"5.04","item":5,"subitem":"04","vetado":false,"descricao":"Inseminação artificial, fertilização in vitro e congêneres."},
  {"codigo":"5.05","item":5,"subitem":"05","vetado":false,"descricao":"Bancos de sangue e de órgãos e congêneres."},
  {"codigo":"5.06","item":5,"subitem":"06","vetado":false,"descricao":"Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."},
  {"codigo":"5.07","item":5,"subitem":"07","vetado":false,"descricao":"Unidade de atendimento, assistência ou tratamento móvel e congêneres."},
  {"codigo":"5.08","item":5,"subitem":"08","vetado":false,"descricao":"Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres."},
  {"codigo":"5.09","item":5,"subitem":"09","vetado":false,"descricao":"Planos de atendimento e assistência médico-veterinária. (Vide Lei Complementar nº 175, de 2020)"},
  {"codigo":"6.01","item":6,"subitem":"01","vetado":false,"descricao":"Barbearia, cabeleireiros, manicuros, pedicuros e congêneres."},
  {"codigo":"6.02","item":6,"subitem":"02","vetado":false,"descricao":"Esteticistas, tratamento de pele, depilação e congêneres."},
  {"codigo":"6.03","item":6,"subitem":"03","vetado":false,"descricao":"Banhos, duchas, sauna, massagens e congêneres."},
  {"codigo":"6.04","item":6,"subitem":"04","vetado":false,"descricao":"Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas."},
  {"codigo":"6.05","item":6,"subitem":"05","vetado":false,"descricao":"Centros de emagrecimento, spa e congêneres."},
  {"codigo":"6.06","item":6,"subitem":"06","vetado":false,"descricao":"Aplicação de tatuagens, piercings e congêneres."},
  {"codigo":"7.01","item":7,"subitem":"01","vetado":false,"descricao":"Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres."},
  {"codigo":"7.02","item":7,"subitem":"02","vetado":false,"descricao":"Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação, concretagem e a instalação e montagem de produtos, peças e equipamentos (exceto o fornecimento de mercadorias produzidas pelo prestador de serviços fora do local da prestação dos serviços, que fica sujeito ao ICMS)."},
  {"codigo":"7.03","item":7,"subitem":"03","vetado":false,"descricao":"Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com obras e serviços de engenharia; elaboração de anteprojetos, projetos básicos e projetos executivos para trabalhos de engenharia."},
  {"codigo":"7.04","item":7,"subitem":"04","vetado":false,"descricao":"Demolição."},
  {"codigo":"7.05","item":7,"subitem":"05","vetado":false,"descricao":"Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres (exceto o fornecimento de mercadorias produzidas pelo prestador dos serviços, fora do local da prestação dos serviços, que fica sujeito ao ICMS)."},
  {"codigo":"7.06","item":7,"subitem":"06","vetado":false,"descricao":"Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres, com material fornecido pelo tomador do serviço."},
  {"codigo":"7.07","item":7,"subitem":"07","vetado":false,"descricao":"Recuperação, raspagem, polimento e lustração de pisos e congêneres."},
  {"codigo":"7.08","item":7,"subitem":"08","vetado":false,"descricao":"Calafetação."},
  {"codigo":"7.09","item":7,"subitem":"09","vetado":false,"descricao":"Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer."},
  {"codigo":"7.10","item":7,"subitem":"10","vetado":false,"descricao":"Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres."},
  {"codigo":"7.11","item":7,"subitem":"11","vetado":false,"descricao":"Decoração e jardinagem, inclusive corte e poda de árvores."},
  {"codigo":"7.12","item":7,"subitem":"12","vetado":false,"descricao":"Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos."},
  {"codigo":"7.13","item":7,"subitem":"13","vetado":false,"descricao":"Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres."},
  {"codigo":"7.14","item":7,"subitem":"14","vetado":true,"descricao":null},
  {"codigo":"7.15","item":7,"subitem":"15","vetado":true,"descricao":null},
  {"codigo":"7.16","item":7,"subitem":"16","vetado":false,"descricao":"Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal e dos serviços congêneres indissociáveis da formação, manutenção e colheita de florestas, para quaisquer fins e por quaisquer meios."},
  {"codigo":"7.17","item":7,"subitem":"17","vetado":false,"descricao":"Escoramento, contenção de encostas e serviços congêneres."},
  {"codigo":"7.18","item":7,"subitem":"18","vetado":false,"descricao":"Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres."},
  {"codigo":"7.19","item":7,"subitem":"19","vetado":false,"descricao":"Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo."},
  {"codigo":"7.20","item":7,"subitem":"20","vetado":false,"descricao":"Aerofotogrametria (inclusive interpretação), cartografia, mapeamento, levantamentos topográficos, batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres."},
  {"codigo":"7.21","item":7,"subitem":"21","vetado":false,"descricao":"Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, estimulação e outros serviços relacionados com a exploração e explotação de petróleo, gás natural e de outros recursos minerais."},
  {"codigo":"7.22","item":7,"subitem":"22","vetado":false,"descricao":"Nucleação e bombardeamento de nuvens e congêneres."},
  {"codigo":"8.01","item":8,"subitem":"01","vetado":false,"descricao":"Ensino regular pré-escolar, fundamental, médio e superior."},
  {"codigo":"8.02","item":8,"subitem":"02","vetado":false,"descricao":"Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza."},
  {"codigo":"9.01","item":9,"subitem":"01","vetado":false,"descricao":"Hospedagem de qualquer natureza em hotéis, apart-service condominiais, flat , apart-hotéis, hotéis residência, residence-service , suite service , hotelaria marítima, motéis, pensões e congêneres; ocupação por temporada com fornecimento de serviço (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."},
  {"codigo":"9.02","item":9,"subitem":"02","vetado":false,"descricao":"Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres."},
  {"codigo":"9.03","item":9,"subitem":"03","vetado":false,"descricao":"Guias de turismo."},
  {"codigo":"10.01","item":10,"subitem":"01","vetado":false,"descricao":"Agenciamento, corretagem ou intermediação de câmbio, de seguros, de cartões de crédito, de planos de saúde e de planos de previdência privada."},
  {"codigo":"10.02","item":10,"subitem":"02","vetado":false,"descricao":"Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer."},
  {"codigo":"10.03","item":10,"subitem":"03","vetado":false,"descricao":"Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária."},
  {"codigo":"10.04","item":10,"subitem":"04","vetado":false,"descricao":"Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil ( leasing ), de franquia ( franchising ) e de faturização ( factoring )."},
  {"codigo":"10.05","item":10,"subitem":"05","vetado":false,"descricao":"Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens ou subitens, inclusive aqueles realizados no âmbito de Bolsas de Mercadorias e Futuros, por quaisquer meios."},
  {"codigo":"10.06","item":10,"subitem":"06","vetado":false,"descricao":"Agenciamento marítimo."},
  {"codigo":"10.07","item":10,"subitem":"07","vetado":false,"descricao":"Agenciamento de notícias."},
  {"codigo":"10.08","item":10,"subitem":"08","vetado":false,"descricao":"Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios."},
  {"codigo":"10.09","item":10,"subitem":"09","vetado":false,"descricao":"Representação de qualquer natureza, inclusive comercial."},
  {"codigo":"10.10","item":10,"subitem":"10","vetado":false,"descricao":"Distribuição de bens de terceiros."},
  {"codigo":"11.01","item":11,"subitem":"01","vetado":false,"descricao":"Guarda e estacionamento de veículos terrestres automotores, de aeronaves e de embarcações."},
  {"codigo":"11.02","item":11,"subitem":"02","vetado":false,"descricao":"Vigilância, segurança ou monitoramento de bens, pessoas e semoventes."},
  {"codigo":"11.03","item":11,"subitem":"03","vetado":false,"descricao":"Escolta, inclusive de veículos e cargas."},
  {"codigo":"11.04","item":11,"subitem":"04","vetado":false,"descricao":"Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie."},
  {"codigo":"11.05","item":11,"subitem":"05","vetado":false,"descricao":"Serviços relacionados ao monitoramento e rastreamento a distância, em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação ou movimento, realizados por meio de telefonia móvel, transmissão de satélites, rádio ou qualquer outro meio, inclusive pelas empresas de Tecnologia da Informação Veicular, independentemente de o prestador de serviços ser proprietário ou não da infraestrutura de telecomunicações que utiliza."},
  {"codigo":"12.01","item":12,"subitem":"01","vetado":false,"descricao":"Espetáculos teatrais."},
  {"codigo":"12.02","item":12,"subitem":"02","vetado":false,"descricao":"Exibições cinematográficas."},
  {"codigo":"12.03","item":12,"subitem":"03","vetado":false,"descricao":"Espetáculos circenses."},
  {"codigo":"12.04","item":12,"subitem":"04","vetado":false,"descricao":"Programas de auditório."},
  {"codigo":"12.05","item":12,"subitem":"05","vetado":false,"descricao":"Parques de diversões, centros de lazer e congêneres."},
  {"codigo":"12.06","item":12,"subitem":"06","vetado":false,"descricao":"Boates, taxi-dancing e congêneres."},
  {"codigo":"12.07","item":12,"subitem":"07","vetado":false,"descricao":"Shows , ballet , danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres."},
  {"codigo":"12.08","item":12,"subitem":"08","vetado":false,"descricao":"Feiras, exposições, congressos e congêneres."},
  {"codigo":"12.09","item":12,"subitem":"09","vetado":false,"descricao":"Bilhares, boliches e diversões eletrônicas ou não."},
  {"codigo":"12.10","item":12,"subitem":"10","vetado":false,"descricao":"Corridas e competições de animais."},
  {"codigo":"12.11","item":12,"subitem":"11","vetado":false,"descricao":"Competições esportivas ou de destreza física ou intelectual, com ou sem a participação do espectador."},
  {"codigo":"12.12","item":12,"subitem":"12","vetado":false,"descricao":"Execução de música."},
  {"codigo":"12.13","item":12,"subitem":"13","vetado":false,"descricao":"Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows , ballet , danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres."},
  {"codigo":"12.14","item":12,"subitem":"14","vetado":false,"descricao":"Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo."},
  {"codigo":"12.15","item":12,"subitem":"15","vetado":false,"descricao":"Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres."},
  {"codigo":"12.16","item":12,"subitem":"16","vetado":false,"descricao":"Exibição de filmes, entrevistas, musicais, espetáculos, shows , concertos, desfiles, óperas, competições esportivas, de destreza intelectual ou congêneres."},
  {"codigo":"12.17","item":12,"subitem":"17","vetado":false,"descricao":"Recreação e animação, inclusive em festas e eventos de qualquer natureza."},
  {"codigo":"13.01","item":13,"subitem":"01","vetado":true,"descricao":null},
  {"codigo":"13.02","item":13,"subitem":"02","vetado":false,"descricao":"Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres."},
  {"codigo":"13.03","item":13,"subitem":"03","vetado":false,"descricao":"Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres."},
  {"codigo":"13.04","item":13,"subitem":"04","vetado":false,"descricao":"Reprografia, microfilmagem e digitalização."},
  {"codigo":"13.05","item":13,"subitem":"05","vetado":false,"descricao":"Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia, exceto se destinados a posterior operação de comercialização ou industrialização, ainda que incorporados, de qualquer forma, a outra mercadoria que deva ser objeto de posterior circulação, tais como bulas, rótulos, etiquetas, caixas, cartuchos, embalagens e manuais técnicos e de instrução, quando ficarão sujeitos ao ICMS."},
  {"codigo":"14.01","item":14,"subitem":"01","vetado":false,"descricao":"Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."},
  {"codigo":"14.02","item":14,"subitem":"02","vetado":false,"descricao":"Assistência técnica."},
  {"codigo":"14.03","item":14,"subitem":"03","vetado":false,"descricao":"Recondicionamento de motores (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."},
  {"codigo":"14.04","item":14,"subitem":"04","vetado":false,"descricao":"Recauchutagem ou regeneração de pneus."},
  {"codigo":"14.05","item":14,"subitem":"05","vetado":false,"descricao":"Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer."},
  {"codigo":"14.06","item":14,"subitem":"06","vetado":false,"descricao":"Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido."},
  {"codigo":"14.07","item":14,"subitem":"07","vetado":false,"descricao":"Colocação de molduras e congêneres."},
  {"codigo":"14.08","item":14,"subitem":"08","vetado":false,"descricao":"Encadernação, gravação e douração de livros, revistas e congêneres."},
  {"codigo":"14.09","item":14,"subitem":"09","vetado":false,"descricao":"Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento."},
  {"codigo":"14.10","item":14,"subitem":"10","vetado":false,"descricao":"Tinturaria e lavanderia."},
  {"codigo":"14.11","item":14,"subitem":"11","vetado":false,"descricao":"Tapeçaria e reforma de estofamentos em geral."},
  {"codigo":"14.12","item":14,"subitem":"12","vetado":false,"descricao":"Funilaria e lanternagem."},
  {"codigo":"14.13","item":14,"subitem":"13","vetado":false,"descricao":"Carpintaria e serralheria."},
  {"codigo":"14.14","item":14,"subitem":"14","vetado":false,"descricao":"Guincho intramunicipal, guindaste e içamento."},
  {"codigo":"15.01","item":15,"subitem":"01","vetado":false,"descricao":"Administração de fundos quaisquer, de consórcio, de cartão de crédito ou débito e congêneres, de carteira de clientes, de cheques pré-datados e congêneres. (Vide Lei Complementar nº 175, de 2020)"},
  {"codigo":"15.02","item":15,"subitem":"02","vetado":false,"descricao":"Abertura de contas em geral, inclusive conta-corrente, conta de investimentos e aplicação e caderneta de poupança, no País e no exterior, bem como a manutenção das referidas contas ativas e inativas."},
  {"codigo":"15.03","item":15,"subitem":"03","vetado":false,"descricao":"Locação e manutenção de cofres particulares, de terminais eletrônicos, de terminais de atendimento e de bens e equipamentos em geral."},
  {"codigo":"15.04","item":15,"subitem":"04","vetado":false,"descricao":"Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade, atestado de capacidade financeira e congêneres."},
  {"codigo":"15.05","item":15,"subitem":"05","vetado":false,"descricao":"Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres, inclusão ou exclusão no Cadastro de Emitentes de Cheques sem Fundos  CCF ou em quaisquer outros bancos cadastrais."},
  {"codigo":"15.06","item":15,"subitem":"06","vetado":false,"descricao":"Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral; abono de firmas; coleta e entrega de documentos, bens e valores; comunicação com outra agência ou com a administração central; licenciamento eletrônico de veículos; transferência de veículos; agenciamento fiduciário ou depositário; devolução de bens em custódia."},
  {"codigo":"15.07","item":15,"subitem":"07","vetado":false,"descricao":"Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo, inclusive por telefone, fac-símile, internet e telex, acesso a terminais de atendimento, inclusive vinte e quatro horas; acesso a outro banco e a rede compartilhada; fornecimento de saldo, extrato e demais informações relativas a contas em geral, por qualquer meio ou processo."},
  {"codigo":"15.08","item":15,"subitem":"08","vetado":false,"descricao":"Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito; estudo, análise e avaliação de operações de crédito; emissão, concessão, alteração ou contratação de aval, fiança, anuência e congêneres; serviços relativos a abertura de crédito, para quaisquer fins."},
  {"codigo":"15.09","item":15,"subitem":"09","vetado":false,"descricao":"Arrendamento mercantil ( leasing ) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia, alteração, cancelamento e registro de contrato, e demais serviços relacionados ao arrendamento mercantil ( leasing ). (Vide Lei Complementar nº 175, de 2020)"},
  {"codigo":"15.10","item":15,"subitem":"10","vetado":false,"descricao":"Serviços relacionados a cobranças, recebimentos ou pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento; fornecimento de posição de cobrança, recebimento ou pagamento; emissão de carnês, fichas de compensação, impressos e documentos em geral."},
  {"codigo":"15.11","item":15,"subitem":"11","vetado":false,"descricao":"Devolução de títulos, protesto de títulos, sustação de protesto, manutenção de títulos, reapresentação de títulos, e demais serviços a eles relacionados."},
  {"codigo":"15.12","item":15,"subitem":"12","vetado":false,"descricao":"Custódia em geral, inclusive de títulos e valores mobiliários."},
  {"codigo":"15.13","item":15,"subitem":"13","vetado":false,"descricao":"Serviços relacionados a operações de câmbio em geral, edição, alteração, prorrogação, cancelamento e baixa de contrato de câmbio; emissão de registro de exportação ou de crédito; cobrança ou depósito no exterior; emissão, fornecimento e cancelamento de cheques de viagem; fornecimento, transferência, cancelamento e demais serviços relativos a carta de crédito de importação, exportação e garantias recebidas; envio e recebimento de mensagens em geral relacionadas a operações de câmbio."},
  {"codigo":"15.14","item":15,"subitem":"14","vetado":false,"descricao":"Fornecimento, emissão, reemissão, renovação e manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."},
  {"codigo":"15.15","item":15,"subitem":"15","vetado":false,"descricao":"Compensação de cheques e títulos quaisquer; serviços relacionados a depósito, inclusive depósito identificado, a saque de contas quaisquer, por qualquer meio ou processo, inclusive em terminais eletrônicos e de atendimento."},
  {"codigo":"15.16","item":15,"subitem":"16","vetado":false,"descricao":"Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo; serviços relacionados à transferência de valores, dados, fundos, pagamentos e similares, inclusive entre contas em geral."},
  {"codigo":"15.17","item":15,"subitem":"17","vetado":false,"descricao":"Emissão, fornecimento, devolução, sustação, cancelamento e oposição de cheques quaisquer, avulso ou por talão."},
  {"codigo":"15.18","item":15,"subitem":"18","vetado":false,"descricao":"Serviços relacionados a crédito imobiliário, avaliação e vistoria de imóvel ou obra, análise técnica e jurídica, emissão, reemissão, alteração, transferência e renegociação de contrato, emissão e reemissão do termo de quitação e demais serviços relacionados a crédito imobiliário."},
  {"codigo":"16.01","item":16,"subitem":"01","vetado":false,"descricao":"Serviços de transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros."},
  {"codigo":"16.02","item":16,"subitem":"02","vetado":false,"descricao":"Outros serviços de transporte de natureza municipal."},
  {"codigo":"17.01","item":17,"subitem":"01","vetado":false,"descricao":"Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista; análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza, inclusive cadastro e similares."},
  {"codigo":"17.02","item":17,"subitem":"02","vetado":false,"descricao":"Datilografia, digitação, estenografia, expediente, secretaria em geral, resposta audível, redação, edição, interpretação, revisão, tradução, apoio e infra-estrutura administrativa e congêneres."},
  {"codigo":"17.03","item":17,"subitem":"03","vetado":false,"descricao":"Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa."},
  {"codigo":"17.04","item":17,"subitem":"04","vetado":false,"descricao":"Recrutamento, agenciamento, seleção e colocação de mão-de-obra."},
  {"codigo":"17.05","item":17,"subitem":"05","vetado":false,"descricao":"Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço."},
  {"codigo":"17.06","item":17,"subitem":"06","vetado":false,"descricao":"Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade, elaboração de desenhos, textos e demais materiais publicitários."},
  {"codigo":"17.07","item":17,"subitem":"07","vetado":true,"descricao":null},
  {"codigo":"17.08","item":17,"subitem":"08","vetado":false,"descricao":"Franquia ( franchising )."},
  {"codigo":"17.09","item":17,"subitem":"09","vetado":false,"descricao":"Perícias, laudos, exames técnicos e análises técnicas."},
  {"codigo":"17.10","item":17,"subitem":"10","vetado":false,"descricao":"Planejamento, organização e administração de feiras, exposições, congressos e congêneres."},
  {"codigo":"17.11","item":17,"subitem":"11","vetado":false,"descricao":"Organização de festas e recepções; bufê (exceto o fornecimento de alimentação e bebidas, que fica sujeito ao ICMS)."},
  {"codigo":"17.12","item":17,"subitem":"12","vetado":false,"descricao":"Administração em geral, inclusive de bens e negócios de terceiros."},
  {"codigo":"17.13","item":17,"subitem":"13","vetado":false,"descricao":"Leilão e congêneres."},
  {"codigo":"17.14","item":17,"subitem":"14","vetado":false,"descricao":"Advocacia."},
  {"codigo":"17.15","item":17,"subitem":"15","vetado":false,"descricao":"Arbitragem de qualquer espécie, inclusive jurídica."},
  {"codigo":"17.16","item":17,"subitem":"16","vetado":false,"descricao":"Auditoria."},
  {"codigo":"17.17","item":17,"subitem":"17","vetado":false,"descricao":"Análise de Organização e Métodos."},
  {"codigo":"17.18","item":17,"subitem":"18","vetado":false,"descricao":"Atuária e cálculos técnicos de qualquer natureza."},
  {"codigo":"17.19","item":17,"subitem":"19","vetado":false,"descricao":"Contabilidade, inclusive serviços técnicos e auxiliares."},
  {"codigo":"17.20","item":17,"subitem":"20","vetado":false,"descricao":"Consultoria e assessoria econômica ou financeira."},
  {"codigo":"17.21","item":17,"subitem":"21","vetado":false,"descricao":"Estatística."},
  {"codigo":"17.22","item":17,"subitem":"22","vetado":false,"descricao":"Cobrança em geral."},
  {"codigo":"17.23","item":17,"subitem":"23","vetado":false,"descricao":"Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar e em geral, relacionados a operações de faturização ( factoring )."},
  {"codigo":"17.24","item":17,"subitem":"24","vetado":false,"descricao":"Apresentação de palestras, conferências, seminários e congêneres."},
  {"codigo":"17.25","item":17,"subitem":"25","vetado":false,"descricao":"Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio (exceto em livros, jornais, periódicos e nas modalidades de serviços de radiodifusão sonora e de sons e imagens de recepção livre e gratuita)."},
  {"codigo":"18.01","item":18,"subitem":"01","vetado":false,"descricao":"Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros; prevenção e gerência de riscos seguráveis e congêneres."},
  {"codigo":"19.01","item":19,"subitem":"01","vetado":false,"descricao":"Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres."},
  {"codigo":"20.01","item":20,"subitem":"01","vetado":false,"descricao":"Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, rebocador escoteiro, atracação, desatracação, serviços de praticagem, capatazia, armazenagem de qualquer natureza, serviços acessórios, movimentação de mercadorias, serviços de apoio marítimo, de movimentação ao largo, serviços de armadores, estiva, conferência, logística e congêneres."},
  {"codigo":"20.02","item":20,"subitem":"02","vetado":false,"descricao":"Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem de qualquer natureza, capatazia, movimentação de aeronaves, serviços de apoio aeroportuários, serviços acessórios, movimentação de mercadorias, logística e congêneres."},
  {"codigo":"20.03","item":20,"subitem":"03","vetado":false,"descricao":"Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros, mercadorias, inclusive suas operações, logística e congêneres."},
  {"codigo":"21.01","item":21,"subitem":"01","vetado":false,"descricao":"Serviços de registros públicos, cartorários e notariais."},
  {"codigo":"22.01","item":22,"subitem":"01","vetado":false,"descricao":"Serviços de exploração de rodovia mediante cobrança de preço ou pedágio dos usuários, envolvendo execução de serviços de conservação, manutenção, melhoramentos para adequação de capacidade e segurança de trânsito, operação, monitoração, assistência aos usuários e outros serviços definidos em contratos, atos de concessão ou de permissão ou em normas oficiais."},
  {"codigo":"23.01","item":23,"subitem":"01","vetado":false,"descricao":"Serviços de programação e comunicação visual, desenho industrial e congêneres."},
  {"codigo":"24.01","item":24,"subitem":"01","vetado":false,"descricao":"Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners , adesivos e congêneres."},
  {"codigo":"25.01","item":25,"subitem":"01","vetado":false,"descricao":"Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico; fornecimento de flores, coroas e outros paramentos; desembaraço de certidão de óbito; fornecimento de véu, essa e outros adornos; embalsamento, embelezamento, conservação ou restauração de cadáveres."},
  {"codigo":"25.02","item":25,"subitem":"02","vetado":false,"descricao":"Translado intramunicipal e cremação de corpos e partes de corpos cadavéricos."},
  {"codigo":"25.03","item":25,"subitem":"03","vetado":false,"descricao":"Planos ou convênio funerários."},
  {"codigo":"25.04","item":25,"subitem":"04","vetado":false,"descricao":"Manutenção e conservação de jazigos e cemitérios."},
  {"codigo":"25.05","item":25,"subitem":"05","vetado":false,"descricao":"Cessão de uso de espaços em cemitérios para sepultamento."},
  {"codigo":"26.01","item":26,"subitem":"01","vetado":false,"descricao":"Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres."},
  {"codigo":"27.01","item":27,"subitem":"01","vetado":false,"descricao":"Serviços de assistência social."},
  {"codigo":"28.01","item":28,"subitem":"01","vetado":false,"descricao":"Serviços de avaliação de bens e serviços de qualquer natureza."},
  {"codigo":"29.01","item":29,"subitem":"01","vetado":false,"descricao":"Serviços de biblioteconomia."},
  {"codigo":"30.01","item":30,"subitem":"01","vetado":false,"descricao":"Serviços de biologia, biotecnologia e química."},
  {"codigo":"31.01","item":31,"subitem":"01","vetado":false,"descricao":"Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres."},
  {"codigo":"32.01","item":32,"subitem":"01","vetado":false,"descricao":"Serviços de desenhos técnicos."},
  {"codigo":"33.01","item":33,"subitem":"01","vetado":false,"descricao":"Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres."},
  {"codigo":"34.01","item":34,"subitem":"01","vetado":false,"descricao":"Serviços de investigações particulares, detetives e congêneres."},
  {"codigo":"35.01","item":35,"subitem":"01","vetado":false,"descricao":"Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas."},
  {"codigo":"36.01","item":36,"subitem":"01","vetado":false,"descricao":"Serviços de meteorologia."},
  {"codigo":"37.01","item":37,"subitem":"01","vetado":false,"descricao":"Serviços de artistas, atletas, modelos e manequins."},
  {"codigo":"38.01","item":38,"subitem":"01","vetado":false,"descricao":"Serviços de museologia."},
  {"codigo":"39.01","item":39,"subitem":"01","vetado":false,"descricao":"Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço)."},
  {"codigo":"40.01","item":40,"subitem":"01","vetado":false,"descricao":"Obras de arte sob encomenda. * (function(){var f5_cspm={f5_p:'DDALMKDDBOHNCGJPEMOPBBCCKJIADFCIIENHPIEHBGDAPHKBDCIGFCMMDKNNEHKEOKABEOKNAAANANLNFIDAKEKDAAFNEMGFDBIODEDLAELALFANDIKOILMODOKIFFNO',setCharAt:function(str,index,chr){if(index>str.length-1)return str;return str.substr(0,index)+chr+str.substr(index+1);},get_byte:function(str,i){var s=(i/16)|0;i=(i&15);s=s*32;return((str.charCodeAt(i+16+s)-65) >4)+65));str=f5_cspm.setCharAt(str,(i+s),String.fromCharCode((b&15)+65));return str;},set_latency:function(str,latency){latency=latency&0xffff;str=f5_cspm.set_byte(str,40,(latency>>8));str=f5_cspm.set_byte(str,41,(latency&0xff));str=f5_cspm.set_byte(str,35,2);return str;},wait_perf_data:function(){try{var wp=window.performance.timing;if(wp.loadEventEnd>0){var res=wp.loadEventEnd-wp.navigationStart;if(res"},
]);
