import { prepararLote, validarPedidoLote } from '../exportacaoLote.js';
import { entriesToCsv } from '../exportacaoIndividual.js';
const pedido={companyIds:['a','b'],competenciaInicio:'2026-08',competenciaFim:'2026-08'};
const entry={id:'e',competencia:'2026-08',data:new Date('2026-08-01T00:00:00Z'),historico:'Receita; teste',tipo:'RECEITA',status:'PENDENTE',lines:[{tipo:'D',conta:'1',valor:123.45},{tipo:'C',conta:'2',valor:123.45}]};
function client(){return {portalClient:{findUnique:jest.fn(async({where})=>({id:where.id,razao:'Empresa '+where.id,cnpj:where.id==='a'?'11111111000111':'22222222000122'}))},accountingEntry:{findMany:jest.fn(async()=>[entry])},chartOfAccount:{findMany:jest.fn(async()=>[{codigo:'1',status:'CONFIRMADO'},{codigo:'2',status:'CONFIRMADO'}])},companyMonthlyCircular:{findUnique:jest.fn(async()=>({fechadoContabilEm:new Date()}))}};}
async function conferir(prisma) {
  const r=await prepararLote({prisma,input:pedido,podeAcessar:async()=>true});
  prisma.accountingEntry.findMany.mockClear();
  return {...pedido,preflightHashes:Object.fromEntries(r.empresas.map(e=>[e.id,e.preflightHash]))};
}
test('valida intervalo civil e limita lote',()=>{expect(()=>validarPedidoLote({...pedido,competenciaFim:'2026-13'})).toThrow();expect(()=>validarPedidoLote({...pedido,competenciaFim:'2026-07'})).toThrow();expect(()=>validarPedidoLote({...pedido,competenciaFim:'2027-08'})).toThrow();});
test('sem acesso não lê cadastro nem lançamentos da empresa',async()=>{const prisma=client();const r=await prepararLote({prisma,input:pedido,podeAcessar:async()=>false,gerarArquivos:true});expect(r.empresas.every(e=>e.estado==='SEM_ACESSO')).toBe(true);expect(prisma.portalClient.findUnique).not.toHaveBeenCalled();expect(prisma.accountingEntry.findMany).not.toHaveBeenCalled();});
test('dois CSVs identificados, sem cabeçalho e mesma data civil/contrato individual',async()=>{const prisma=client();const input=await conferir(prisma);const r=await prepararLote({prisma,input,podeAcessar:async()=>true,gerarArquivos:true});expect(r.arquivos).toHaveLength(2);expect(r.arquivos[0].nome).toBe('11111111000111-2026-08_2026-08.csv');expect(r.arquivos[0].conteudo).toBe('\uFEFF'+entriesToCsv([entry]));expect(r.arquivos[0].conteudo).toContain('01/08/2026;1;2;Receita  teste;123,45');expect(prisma.accountingEntry.findMany).toHaveBeenCalledTimes(2);});
test('recusa conta fora do plano e não gera CSV inválido',async()=>{const prisma=client();prisma.chartOfAccount.findMany.mockResolvedValue([]);const r=await prepararLote({prisma,input:pedido,podeAcessar:async()=>true,gerarArquivos:true});expect(r.arquivos).toHaveLength(0);expect(r.empresas[0].estado).toBe('BLOQUEADA');});
test('falha parcial mantém resultado das outras empresas',async()=>{const prisma=client();const input=await conferir(prisma);prisma.portalClient.findUnique.mockRejectedValueOnce(new Error('offline'));const r=await prepararLote({prisma,input,podeAcessar:async()=>true,gerarArquivos:true});expect(r.empresas.map(e=>e.estado)).toEqual(['FALHA','EXPORTADA']);expect(r.arquivos).toHaveLength(1);});
test('alerta de mês aberto exige confirmação e prévia não expõe linhas internas',async()=>{const prisma=client();prisma.companyMonthlyCircular.findUnique.mockResolvedValue(null);const input=await conferir(prisma);const r=await prepararLote({prisma,input,podeAcessar:async()=>true,gerarArquivos:true});expect(r.empresas[0].estado).toBe('AGUARDA_CONFIRMACAO');const ok=await prepararLote({prisma,input:{...input,confirmarAlertas:true},podeAcessar:async()=>true,gerarArquivos:true});expect(ok.arquivos).toHaveLength(2);expect(ok.empresas[0].entries).toBeUndefined();});
test('novo alerta invalida só empresa afetada, mesmo com checkbox confirmado',async()=>{const prisma=client();const input=await conferir(prisma);prisma.companyMonthlyCircular.findUnique.mockImplementation(async({where})=>where.portalClientId_competencia.portalClientId==='a'?null:{fechadoContabilEm:new Date()});const r=await prepararLote({prisma,input:{...input,confirmarAlertas:true},podeAcessar:async()=>true,gerarArquivos:true});expect(r.empresas.map(e=>e.estado)).toEqual(['PREVIA_ALTERADA','EXPORTADA']);expect(r.empresas[0].motivo).toMatch(/Confira novamente/);expect(r.arquivos).toHaveLength(1);expect(r.arquivos[0].nome).toMatch(/^22222222/);});
test('hash é vinculado a empresa e período; ausência de prévia não exporta',async()=>{const prisma=client();const input=await conferir(prisma);input.preflightHashes.b=input.preflightHashes.a;const r=await prepararLote({prisma,input,podeAcessar:async()=>true,gerarArquivos:true});expect(r.empresas.map(e=>e.estado)).toEqual(['EXPORTADA','PREVIA_ALTERADA']);const outro=await prepararLote({prisma,input:{...input,competenciaFim:'2026-09'},podeAcessar:async()=>true,gerarArquivos:true});expect(outro.arquivos).toHaveLength(0);const sem=await prepararLote({prisma,input:pedido,podeAcessar:async()=>true,gerarArquivos:true});expect(sem.arquivos).toHaveLength(0);});
