import { Prisma } from '@prisma/client';
import { compararValores, definirPeriodos, montarAnalise } from '../analiseEmpresa.js';
const plano=new Map([['1',{codigo:'1',codigoCompleto:'31101',nome:'Receita'}],['2',{codigo:'2',codigoCompleto:'41102001',nome:'Aluguel'}]]);
const entry=(mes,conta,tipo,valor,status='CONFIRMADO')=>({competencia:mes,status,lines:[{conta,tipo,valor:new Prisma.Decimal(valor)}]});
const dados=()=>({circulares:['2026-07','2026-08'].map(competencia=>({competencia,fechadoContabilEm:'2026-09-01'})),periodos:definirPeriodos({de:'2026-08',ate:'2026-08'}),plano,hoje:'2026-09-10',lancamentos:[entry('2026-08','1','C',1000),entry('2026-08','2','D',200),entry('2026-07','1','C',800)],notas:[{competencia:'2026-08-01',total:1000}],guias:[{id:'a',competencia:'2026-08',tipo:'SIMPLES',valor:100,status:'PROCESSED',paymentStatus:'OPEN',vencimento:'2026-09-20'},{id:'b',competencia:'2026-08',tipo:'PARC SN',parcelamentoId:'p',valor:500,status:'PROCESSED',paymentStatus:'OPEN',vencimento:'2026-08-28'}]});
test('comparação por ano e duração, incluindo virada de ano',()=>{expect(definirPeriodos({de:'2026-01',ate:'2026-08',comparar:'ano'}).anterior).toEqual({de:'2025-01',ate:'2025-08'});expect(definirPeriodos({de:'2026-01',ate:'2026-03'}).anterior).toEqual({de:'2025-10',ate:'2025-12'});expect(()=>definirPeriodos({de:'2026-13',ate:'2026-14'})).toThrow();});
test('Decimal, DRE e parcelamento fora da carga',()=>{const r=montarAnalise(dados());expect(r.atual.indicadores).toMatchObject({faturamento:1000,resultado:800,despesas:200,tributos:100,carga:10,margemLiquida:80});expect(r.guias).toHaveLength(2);});
test('ausência não é zero e não dispara crescimento',()=>{const r=montarAnalise({...dados(),lancamentos:[],notas:[],guias:[]});expect(r.atual.indicadores.resultado).toBeNull();expect(r.atual.indicadores.faturamento).toBeNull();expect(r.insights).toEqual([]);});
test('zero documental só é confirmado por declaração da competência',()=>{const r=montarAnalise({...dados(),notas:[],circulares:[{competencia:'2026-08',semFaturamento:true,fechadoContabilEm:'2026-09-01'}]});expect(r.atual.indicadores.faturamento).toBe(0);expect(r.anterior.indicadores.faturamento).toBeNull();expect(r.cobertura.at(-1).semFaturamentoConfirmado).toBe(true);});
test('rascunho torna análise provisória e silencia alertas de evolução',()=>{const d=dados();d.lancamentos[0].status='RASCUNHO';const r=montarAnalise(d);expect(r.atual.parcial).toBe(true);expect(r.insights.every(i=>i.secao==='impostos')).toBe(true);});
test('margem do acumulado é razão de somas',()=>{const d=dados();d.periodos=definirPeriodos({de:'2026-07',ate:'2026-08'});expect(montarAnalise(d).atual.indicadores.margemLiquida).toBeCloseTo(1600/1800*100);});
test('zero e prejuízo não criam percentual enganoso',()=>{expect(compararValores(20,0).percentual).toBeNull();expect(compararValores(20,-10).texto).toMatch(/Reversão/);expect(compararValores(null,10).absoluta).toBeNull();expect(compararValores(12,10,true).texto).toBe('+2.00 p.p.');});
test('guias inválidas não somam e nota sem valor não vira zero',()=>{const d=dados();d.notas[0].total=null;d.guias[0].status='ERROR';const r=montarAnalise(d);expect(r.atual.indicadores.faturamento).toBeNull();expect(r.atual.indicadores.tributos).toBeNull();expect(r.avisos.join(' ')).toMatch(/processadas/);});

test('fechamento contábil é obrigatório e reabertura invalida dados',()=>{const d=dados();d.circulares=[];expect(()=>montarAnalise(d)).toThrow(/Feche a contabilidade/);});
test('atual fechado permanece acessível, anterior aberto e série sem valores',()=>{const d=dados();d.circulares=d.circulares.filter(c=>c.competencia==='2026-08');const r=montarAnalise(d);expect(r.atual.indicadores.resultado).toBe(800);expect(r.anterior.indisponivel).toBe(true);expect(r.anterior.indicadores.resultado).toBeNull();expect(r.anterior.dre.linhas.every(l=>l.valor===null&&l.contas.length===0)).toBe(true);expect(r.variacoes.resultado.percentual).toBeNull();expect(r.serie.find(m=>m.competencia==='2026-07').indicadores.faturamento).toBeNull();});
test('mês calendário atual pode aparecer quando contabilidade está fechada',()=>{const d=dados();d.hoje='2026-08-15';expect(montarAnalise(d).atual.indicadores.resultado).toBe(800);});
