import { confirmarPagamentoWhatsapp,lerDataWhatsapp,chaveFluxoPagamento } from '../ConfirmarPagamentoWhatsappService.js';
const id='altan.payment.confirm.11111111-1111-4111-8111-111111111111';
function preparar(){const value={companyId:'c',guideId:'g',contatoId:'ct',telefone:'5511999999999',expiraEm:'2026-10-01T00:00:00Z'};const rows=new Map([[id,value]]);const guia={id:'g',tipo:'FGTS',competencia:null,paymentStatus:'OPEN',updatedAt:new Date(),baixada:false};
 const tx={appSetting:{findUnique:jest.fn(async({where})=>rows.has(where.key)?{value:rows.get(where.key)}:null),create:jest.fn(async({data})=>rows.set(data.key,data.value)),update:jest.fn(async({where,data})=>rows.set(where.key,data.value)),upsert:jest.fn(async({where,create,update})=>rows.set(where.key,rows.has(where.key)?update.value:create.value))},contatoWhatsapp:{findFirst:jest.fn(async()=>({id:'ct',userId:null}))},guide:{findFirst:jest.fn(async()=>guia),updateMany:jest.fn(async({data})=>{Object.assign(guia,data);return{count:1};})},arquivoWhatsapp:{findUnique:jest.fn(async()=>({id:'ar',portalClientId:'c'})),updateMany:jest.fn(async()=>({count:1}))}};
 const client={...tx,$transaction:jest.fn(fn=>fn(tx))};const args={id,conversa:{id:'cv',portalClientId:'c',telefoneE164:value.telefone},mensagem:{id:'m',tipo:'interactive',direcao:'in',conversaId:'cv'},client,conferirAcesso:jest.fn(async()=>{}),agora:new Date('2026-09-25T12:00:00Z')};let seq=0;
 return{value,rows,guia,tx,args,run:()=>confirmarPagamentoWhatsapp(args),responder:async(corpo,extra={})=>{args.id=null;args.mensagem={...args.mensagem,id:'r'+(++seq),tipo:'text',corpo,...extra};return confirmarPagamentoWhatsapp(args);}};
}
test('clique pede data; só a resposta válida marca pagamento, sem baixa',async()=>{const f=preparar();expect((await f.run()).texto).toContain('Em que data');expect(f.tx.guide.updateMany).not.toHaveBeenCalled();expect((await f.responder('20/09/2026')).texto).toContain('20/09/2026');expect(f.guia).toMatchObject({paymentStatus:'PAID',paymentStatusSource:'CLIENTE',paymentConfirmedAt:new Date('2026-09-20'),baixada:false});await f.run();expect(f.tx.guide.updateMany).toHaveBeenCalledTimes(1);await f.responder('sem comprovante');expect(f.rows.get(chaveFluxoPagamento(f.args.conversa)).etapa).toBeNull();});
test.each(['31/02/2026','26/09/2026','ontem','15'])('data %s não inventa pagamento',async data=>{const f=preparar();await f.run();await f.responder(data);expect(f.tx.guide.updateMany).not.toHaveBeenCalled();});
test.each(['empresa','telefone','expirado','contato','guia','saida'])('recusa %s',async tipo=>{const f=preparar();if(tipo==='empresa')f.args.conversa.portalClientId='outra';if(tipo==='telefone')f.args.conversa.telefoneE164='outro';if(tipo==='expirado')f.value.expiraEm='2026-09-20';if(tipo==='contato')f.tx.contatoWhatsapp.findFirst.mockResolvedValue(null);if(tipo==='guia')f.tx.guide.findFirst.mockResolvedValue(null);if(tipo==='saida')f.args.mensagem.direcao='out';expect((await f.run()).texto).toContain('Não foi possível');expect(f.tx.guide.updateMany).not.toHaveBeenCalled();});
test('comprovante fica vinculado sem substituir declaração por prova automática',async()=>{const f=preparar();await f.run();await f.responder('20/09/2026');await f.responder('',{tipo:'image',midiaProvedorId:'123'});expect(f.tx.arquivoWhatsapp.updateMany).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({comprovanteGuiaId:'g',dataPagamentoDeclarada:new Date('2026-09-20')})}));expect(f.guia.paymentStatusSource).toBe('CLIENTE');});
test('não vincula arquivo de outra empresa',async()=>{const f=preparar();await f.run();await f.responder('20/09/2026');f.tx.arquivoWhatsapp.findUnique.mockResolvedValue({id:'ar',portalClientId:'outro'});await f.responder('',{tipo:'document',midiaProvedorId:'123'});expect(f.tx.arquivoWhatsapp.updateMany).not.toHaveBeenCalled();});
test('hoje respeita o calendário de São Paulo na virada UTC',()=>{expect(lerDataWhatsapp('hoje',new Date('2026-09-26T01:00Z')).data).toEqual(new Date('2026-09-25'));});
test('pagamento oficial concorrente é preservado',async()=>{const f=preparar();await f.run();Object.assign(f.guia,{paymentStatus:'PAID',paymentStatusSource:'SERPRO'});await f.responder('20/09/2026');expect(f.tx.guide.updateMany).not.toHaveBeenCalled();});
test('cancelamento não marca como paga',async()=>{const f=preparar();await f.run();await f.responder('cancelar pagamento');expect(f.tx.guide.updateMany).not.toHaveBeenCalled();});
test('revogação antes da gravação impede a declaração',async()=>{const f=preparar();await f.run();f.args.conferirAcesso.mockRejectedValueOnce(Error('revogado'));await expect(f.responder('20/09/2026')).rejects.toThrow('revogado');expect(f.tx.guide.updateMany).not.toHaveBeenCalled();});

test('arquivo sem empresa só é atribuído com origem no mesmo telefone e canal',async()=>{const f=preparar();await f.run();await f.responder('20/09/2026');f.tx.arquivoWhatsapp.findUnique.mockResolvedValue({id:'ar',portalClientId:null,mensagem:{conversa:{telefoneE164:f.args.conversa.telefoneE164,canalId:'principal'}}});await f.responder('',{tipo:'image',midiaProvedorId:'123'});expect(f.tx.arquivoWhatsapp.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({portalClientId:null}),data:expect.objectContaining({portalClientId:'c',comprovanteGuiaId:'g'})}));});
